### ISSUE TITLE
Flatpak support

### ISSUE THREAD

**Issue by Murmele** [horizon-eda/horizon#121]
I'm working on creating a [flatpak](https://flatpak.org/) package. For this I would ask if the pool manager should be in the package or should it be manually installed?

**Comment by greenscreenflicker** [comment]
You require the pool manager to create new packages...

**Comment by carrotIndustries** [comment]
Don't forget to include the horizon-imp binary as well since that's the actual editor called from the pool and project manager.

**Comment by Murmele** [comment]
Thank you for you hints, hope to get finish the flatpak package :)

**Comment by Murmele** [comment]
Here you can find the Flatpak manifest for horizon.
https://github.com/Murmele/horizon/tree/flatpak
First the branch of peterus "switch_to_cmake" must be merged

**Comment by carrotIndustries** [comment]
It's on flatpak https://flathub.org/apps/details/org.horizon_eda.HorizonEDA
