### ISSUE TITLE
KiCad Footprint import tool

### ISSUE THREAD

**Issue by greenscreenflicker** [horizon-eda/horizon#142]
I propose an import tool for KiCad footprints, as it would allow to benefit from the large KiCad resource.

**Comment by niclashoyer** [comment]
Is this done with 16af8124f76af2cf8ae368586b17c0f62786232f?

**Comment by carrotIndustries** [comment]
> Is this done with 16af812?

Yes. There's still some work to be done to handle arcs and other stuff, but good enough for now.
