### ISSUE TITLE
DXF files wont show up in file selector

### ISSUE THREAD

**Issue by atoav** [horizon-eda/horizon#226]
## Problem
I'd like to import a DXF file I made in adobe Illustrator for a Panel I made (in order to convert it to Gerber). However, it doesn't show up in the File chooser. I don't know Gtk, but the file choosers I am familiar with only filter based on file extensions. The extension here clearly is `.dxf`. so it could be a Windows issue? How are these files filtered?  

## File Chooser:  
![2019-01-22 00_15_29-import dxf](https://user-images.githubusercontent.com/6620266/51503361-e430f300-1dda-11e9-8b81-a4dbc890138e.png)  

## In Explorer:  
![2019-01-22 00_17_54-vvca](https://user-images.githubusercontent.com/6620266/51503420-35d97d80-1ddb-11e9-98f1-c19a8788b064.png)

**Comment by carrotIndustries** [comment]
Seems like MIME types aren't a thing on windows: a5489789c9c46adaad28a4a7f26a91debca611b6 changed this dialog to use pattern matching instead of looking at the MIME type.

**Comment by atoav** [comment]
Wow that was fast, I will try it as soon as it has compiled.

**Comment by atoav** [comment]
The problem I had is resolved, Now I only need to figure out how to get my filled surfaces into solid planes. I guess I will have to slice the shapes into sub-shapes without "holes" or "islands" and then use the line loop to polygon tool on each sub-shape.
