### ISSUE TITLE
Cloning community pool doesn't work: HTTP 301 response

### ISSUE THREAD

**Issue by atoav** [horizon-eda/horizon#261]
I suspect this has to do with the recent move:  
![2019-05-12 23_34_50-Horizon EDA](https://user-images.githubusercontent.com/6620266/57588049-b6e58d80-750e-11e9-8dd2-d1baa44b7e3f.png)  

At the same time my pool fails to load up with the Error:  
![2019-05-12 23_38_55-Pool manager](https://user-images.githubusercontent.com/6620266/57588075-40955b00-750f-11e9-971d-04d82d99271f.png)

I have to investigate further, to figure out what's going on

**Comment by atoav** [comment]
I tried with a newer build 3cb41189, and have the same happening to me. Manually cloning and opening the pool works, but for some reason my own pool fails with that UUID error, still investigating...

**Comment by carrotIndustries** [comment]
The first problem is solved by dfa9fad3d884b31c1a987e3d99dd3cf84acdd9a6 and db12787592138cde53a9ab3c567da0a93d20457d

However, I can't think of a reason for the second one...

**Comment by atoav** [comment]
I tried copying the working `pool.json` from upstream/master to my pool, with no success. How can I trace down the origin of that invalid UUID?

**Comment by carrotIndustries** [comment]
> How can I trace down the origin of that invalid UUID?

 - Compile horizon from source so that you have debug symbols
 - From the mingw shell, run `gdb ./horizon-eda`
 - In the gdb shell:
 - `catch throw`
- `run`
- Do the action that causes the error
- in the gdb shell, type `bt` to get the backtrace

You may also try deleting the `pool.db` and `parametric.db` file.

**Comment by atoav** [comment]
Thanks, I solved it. I just cloned my pool freshly and set up the remote to the new URL. For some reason it now works. The remote adress shouldn't have anything to do with it, but the problem seems solved now : )

**Comment by atoav** [comment]
Okay also figured out the cause:

I was trying to work out a new `table.json` for polarized capacitors and this seems to have impacted the `parametric.db`. See the file here: https://gist.github.com/atoav/0abd403bdb419a85e964e240c261e309

**Comment by atoav** [comment]
Okay very cool this works. Only a short hint:
![2019-05-13 01_04_50-Pool manager](https://user-images.githubusercontent.com/6620266/57588852-34af9600-751b-11e9-937f-d59dcf0e95a5.png)
  
Is there any way to format the hours and the temperature here without exponent?
