### ISSUE TITLE
Rule to check that refdes' are unique

### ISSUE THREAD

**Issue by frmdstryr** [horizon-eda/horizon#267]
If a refdes is duplicated I don't see any warnings. Should there be a schematic rule to check for this?

**Comment by carrotIndustries** [comment]
Unsure whether to make this a warning (same as duplicate net names) or an actual rule. I'm gravitating towards a warning since this is something computationally simple to figure out and immediate feedback is nice to have.

**Comment by frmdstryr** [comment]
Yeah a warning makes sense.  I'm not

**Comment by frmdstryr** [comment]
Works great, thanks!
