### ISSUE TITLE
Crash when dragging one square onto another onto another

### ISSUE THREAD

**Issue by atoav** [horizon-eda/horizon#276]
## Problem

Moving certain geometry on top of each other crashes the parent window of an editor e.g. with status -1073741819. I had this multiple times already in the schematic editor, only now managed to check how to boil it down to a minimum reproducible case.

## Steps to replicate

1. draw two lines besides each other with some space inbetween
2. take one line and move it onto the other linein such a way, that a junktion of line A touches the junktion on line B
3. Boom

A vague unbased suspect might be the merging of junctions. This definitly needs fixing as it destroys unsaved changes without a warning.

**Comment by carrotIndustries** [comment]
Unfortunately, I can't reproduce this error. Can you share a test project and perhaps a short screen capture to help me reproduce this?

**Comment by atoav** [comment]
Ok, I could reproduce it with:
- the latest build
- deleted startup folder
- community pool
- new empty project

This is as vanilla as it gets. Here you can see me drawing the two lines then moving one onto the other using <kbd>m</kbd>, at which point it crashes:  

![N9AVS7DX3N](https://user-images.githubusercontent.com/6620266/58502037-ff937c80-8185-11e9-8bf4-f367ffc4fa4c.gif)

I run on Microsoft Windows Version 1809 (OS Build 17763.503) with `0.9.0 Aurora Commit f5f307b 2019-05-26 18:44:52 +0200 warnings for duplicate refdes`

**Comment by carrotIndustries** [comment]
Duh, I extrapolated that lines == net lines

**Comment by atoav** [comment]
Oh sorry for the miscommunication

**Comment by carrotIndustries** [comment]
Anyhow, thanks for reporting this. Running into things like these within the first moments of using the schematic editor can really ruin one's overall impression.
