### ISSUE TITLE
Version information in .hprj?

### ISSUE THREAD

**Issue by fruchti** [horizon-eda/horizon#280]
Since .hprj files are human-readable and rather short, it could be useful to have some information about the Horizon version used to create the project in them. For example, if an old, archived project could no longer be opened with the current Horizon version for some reason, it would be very useful to be able to compile a working Horizon. If the information is machine-readable, Horizon could check if a project was created with a newer version and warn the user information may be lost when editing/saving the project with the older, currently installed version.

For a human-readable field the format in the About dialogue should be sensible. An automated version check probably works best with the commit timestamp and hash?

**Comment by carrotIndustries** [comment]
> An automated version check probably works best with the commit timestamp and hash?

That'd generate too many false positives I suppose. Storing the major/minor/micro version and do the check based on that one seems to be a better way.

**Comment by fruchti** [comment]
> > An automated version check probably works best with the commit timestamp and hash?
> 
> That'd generate too many false positives I suppose. Storing the major/minor/micro version and do the check based on that one seems to be a better way.

You're right. TBH, I wasn't aware there was already a version number, since the repository lists no releases. The stored version information should contain the commit hash, though, for the slight chance that some corner case breaks without a version number bump.

**Comment by carrotIndustries** [comment]
We now have version information all pool/project files.

When opening a new file with an old version:
![2020-10-18-173420_501x556_scrot](https://user-images.githubusercontent.com/877304/96372679-3ba6f300-1168-11eb-84f5-c1f2fc561e7c.png)

Before saving a file in a new version:
![2020-10-18-173307_534x380_scrot](https://user-images.githubusercontent.com/877304/96372680-3c3f8980-1168-11eb-96d2-93200a30e40e.png)
