### ISSUE TITLE
[UX] Minor Improvment: Set Zoom to Fit when Schematic is opened

### ISSUE THREAD

**Issue by atoav** [horizon-eda/horizon#281]
This is just a minor thing, but I noticed that horizon has some sort of default zoom level it recalls once you reopen a project. Uppon opening a schematic I always hit <kbd>Home</kbd> right away – maybe it would be reasonable to do this automatically for all sheets?

This allows you to get a "overview" first and then you can zoom in onto the parts that interest you – so it fits with the cognitive flow.

**Comment by carrotIndustries** [comment]
Have a look at that branch and see if it works for you.

The whole thing is a bit hacky since we can't really tell if that's the first size-allocate is the final one visible to the user.

**Comment by atoav** [comment]
Hey cool, it sort of improved things, but it is not _quite_ there for some reason. Pictures speak more than a thousand words so see here:

| master behaviour | branch behaviour | after pressing <kbd>Home</kbd> |
| --- | --- | --- |
|  ![home_0](https://user-images.githubusercontent.com/6620266/59588982-2f7cd280-90e9-11e9-8eac-b9fd66314501.png) | ![home_1](https://user-images.githubusercontent.com/6620266/59588990-3572b380-90e9-11e9-8d6c-33703e6126e3.png) | ![home_2](https://user-images.githubusercontent.com/6620266/59589001-3acffe00-90e9-11e9-82cb-8ca1c4955b63.png) |

The first one is how it looks when I open the project on the master build. The second one is how it looks when you open it on the new branch. The third one is how it looks when you zoom to fit.

We can leave it like that, it is already an improvement.
