### ISSUE TITLE
Assembly view export

### ISSUE THREAD

**Issue by atoav** [horizon-eda/horizon#286]
Currently I am taking screenshots of the Assembly view and combine them to get a high resolution image which I then recolor and write a legend for.

I don't have to do that very often so it is not a pressing issue, but I know you have a export assembly view feature planed so I was curious about how it would look like?

Maybe for starters a `Export visible Layers as PDF` similar to the thing in the schematic editor would be totally enough?

**Comment by carrotIndustries** [comment]
I've had something similar to altium's draftsman in mind for implementing assembly drawing export: https://www.altium.com/documentation/19.0/display/ADES/((Draftsman))_AD

However, since that's likely to be a significant effort, something a bit more basic seems to be a reasonable idea.

**Comment by fruchti** [comment]
I've thought about this lately as well. I think the “Export visible Layers as PDF” option would be a very reasonable solution that would remain useful as a “quick export” even when a more powerful tool comes along.

**Comment by carrotIndustries** [comment]
> However, since that's likely to be a significant effort, something a bit more basic seems to be a reasonable idea.

done in 1e1f308a1faa51541c2290c1afb081d2163cd5a4

**Comment by fruchti** [comment]
This is great, thanks a lot!

**Comment by atoav** [comment]
Very cool, works like a charm and does the job!

**Comment by carrotIndustries** [comment]
Closing since everyone seems to be content with  1e1f308.
