### ISSUE TITLE
[UX] Feature Request: Indicate whether item is already selected in selection context menu

### ISSUE THREAD

**Issue by frmdstryr** [horizon-eda/horizon#289]
When I drag and select a bunch of components then attempt to deselect some, it's sometimes difficult to know which is selected or not when the selection menu pops up.  It would be nice if the menu would somehow indicate which item(s) are currently selected.

**Comment by carrotIndustries** [comment]
Okay, I got something working that just appends `(selected)` to the menu item. Got any better idea?

**Comment by frmdstryr** [comment]
That should work or maybe a [CheckMenuItem](https://developer.gnome.org/pygtk/stable/class-gtkcheckmenuitem.html) might look better if it's not hard to change to that?

![image](https://user-images.githubusercontent.com/380158/61241881-74108380-a712-11e9-9f22-9e986728ad84.png)

**Comment by frmdstryr** [comment]
Works great, thanks!
