### ISSUE TITLE
Compiling on Debian 10

### ISSUE THREAD

**Issue by Peta-T** [horizon-eda/horizon#297]
Hello,
I have fresh installed Debian 10 and successful compiled Horizon-EDA
with this dependencies
su
apt install libgtkmm-3.0-dev
apt install libcairomm-1.0-dev
apt install librsvg2-dev
apt install util-linux
apt install libyaml-cpp-dev
apt install libsqlite3-dev
apt install libboost-all-dev
apt install libzmq3-dev
apt install libglm-dev
apt install libgit2-dev
apt install libcurl3-dev
apt install liboce-ocaf-dev
apt install libpodofo-dev
apt install libzip-dev
apt install git
exit

git clone http://github.com/carrotIndustries/horizon
cd horizon
make -j 4

it is OK

but  when I open my older project found mistake on top layer
![Snímek z 2019-09-27 17-16-52](https://user-images.githubusercontent.com/16006267/65780891-f671e680-e14a-11e9-93e3-7f137b9b1101.png)
with this error
![Snímek z 2019-09-27 17-20-43](https://user-images.githubusercontent.com/16006267/65781049-3cc74580-e14b-11e9-9476-6915f16b1d42.png)
how can I repair it
Thanks
P

**Comment by carrotIndustries** [comment]
The issue isn't with debian 10. The library used for triangulation has the bad habit of crashing when provided with input it doesn't like such as duplicate points.

Have a look at the position mentioned in the log window and watch out for solder mask features that touch each other at exactly one point and the like.

**Comment by Peta-T** [comment]
OK,
according coordinates in logs I found that if i remove 2 vias all is ok and if I put this vias again in litle different positions all is ok
Thanks.

![Snímek z 2019-09-29 12-39-38](https://user-images.githubusercontent.com/16006267/66272790-60d30700-e86e-11e9-88d8-7c3a83172501.png)
![Snímek z 2019-09-29 12-40-12](https://user-images.githubusercontent.com/16006267/66272793-64ff2480-e86e-11e9-8b81-077e777455aa.png)

![Snímek z 2019-09-29 12-41-05](https://user-images.githubusercontent.com/16006267/66272847-dd65e580-e86e-11e9-9a97-4b45d15f5c63.png)
