### ISSUE TITLE
open drain pin indicator positioned incorrectly on mirrored symbols

### ISSUE THREAD

**Issue by eqvinox** [horizon-eda/horizon#298]
![horizon_od_indicator](https://user-images.githubusercontent.com/1715611/66082923-7e048e80-e56b-11e9-937a-264e6ee7039c.png)

Both U605 and U? (AP22615) symbols are mirrored, causing the OD indicator on their FLT/FLG pins to be positioned wrong.  Rendering is correct when the symbols are not mirrored.

(Ignore my crappy symbols :disappointed:)

**Comment by carrotIndustries** [comment]
ah, coordinate transformations, the bane of my existence
