### ISSUE TITLE
Additional silkscreen text disappears when smashing package

### ISSUE THREAD

**Issue by fruchti** [horizon-eda/horizon#314]
I was hoping to be able to move around all text fields on a silkscreen layer by smashing it in the board editor. Instead, all text except for the reference designator just disappears.

**Comment by carrotIndustries** [comment]
I cannot reproduce this issue. I added another text on the silkscreen layer of a package, placed in on a board and smashed it. Everything worked as expected.

**Comment by fruchti** [comment]
Interesting, it is definitely happening for me (a clean rebuild and starting with the default configuration both didn't help). [Here's a package I used for testing.](https://github.com/horizon-eda/horizon/files/3819583/package.zip)

**Comment by fruchti** [comment]
Thanks!
