### ISSUE TITLE
Description in org.horizon_eda.HorizonEDA.metainfo.xml is a bit short

### ISSUE THREAD

**Issue by steinm** [horizon-eda/horizon#327]
Just a minor thing. According to https://appstream.debian.org/sid/main/issues/horizon-eda.html the description is somewhat short.

**Comment by carrotIndustries** [comment]
Yeah, that's why the flathub PR still is WIP. Feel free to make suggestions for a more elaborate description.

**Comment by steinm** [comment]
From the documentation of horizon-eda

Horizon EDA is a Electronics Design Application similar to tools like KiCAD or LibrePCB. It allows you to draw schematics, layout circuit boards and comfortably manage a parts collection.

**Comment by carrotIndustries** [comment]
I'm not particularly happy with that description either as it references other applications. The description should be self-contained without comparing to other apps.

**Comment by steinm** [comment]
How about:

Horizon EDA is an Electronics Design Application. It covers the complete design flow from schematic entry to gerber export and includes a unified editor for parts, the schematic and board.

**Comment by carrotIndustries** [comment]
got fixed in ce364699521e23a5d772b056b459dac81ebc8d17
