### ISSUE TITLE
Edit multiple vias

### ISSUE THREAD

**Issue by endofexclusive** [horizon-eda/horizon#344]
# Use case
Change the size of all fanout vias under a BGA package, but leave all other vias on the board as is.

# Suggestion 1
Present the via parameters (`Hole diameter` and `Via diameter`) for selected vias in the right-side property panel. Similar to when multiple tracks are selected.

# Suggestion 2
Adapt the `Edit via` dialog so that it can be used also when more than one via is selected.

**Comment by carrotIndustries** [comment]
> Adapt the Edit via dialog so that it can be used also when more than one via is selected.

That's the way to go since we already have that for holes.

**Comment by carrotIndustries** [comment]
closed by #346
