### ISSUE TITLE
update appdata release version

### ISSUE THREAD

**Issue by eszlari** [horizon-eda/horizon#348]
Flathub (https://flathub.org/apps/details/org.horizon_eda.HorizonEDA) still shows 0.9.7 for the 1.0.0 release.

**Comment by carrotIndustries** [comment]
Good catch, do you see any other method to fix this than doing an 1.0.1 release? (Same content as 1.0.0, only different version number)

**Comment by eszlari** [comment]
Simply add a patch to the Flathub repository?!

**Comment by carrotIndustries** [comment]
Great idea, see https://github.com/flathub/org.horizon_eda.HorizonEDA/commit/fb66379399d7a937b3fcc9b98c8b4ee801a2a766

I'll close the issues once the build is done.

**Comment by carrotIndustries** [comment]
Build went well: https://flathub.org/apps/details/org.horizon_eda.HorizonEDA
