### ISSUE TITLE
Delete pools option in startup menu 

### ISSUE THREAD

**Issue by greenscreenflicker** [horizon-eda/horizon#349]
There is missing a delete option on startup for the pool manager.
See image attached. I propose a rightclick on pool, to to delete those.

![grafik](https://user-images.githubusercontent.com/17407241/75801214-0c7b7700-5d7b-11ea-9719-d5b928f1afd7.png

**Comment by carrotIndustries** [comment]
Are you referring to deleting the pool folder from disk or just removing them from the recent pools list?

**Comment by greenscreenflicker** [comment]
I would propose to remove them from the pool list. Then a dialog pops up asking if you want to remove it from disk.

**Comment by carrotIndustries** [comment]
rather then offering a option to delete things from disk, I added a menu item to open the pool/project in the file browser

**Comment by greenscreenflicker** [comment]
@carrotIndustries Lukas, thanks, I will test soon and give feedback.

**Comment by greenscreenflicker** [comment]
@carrotIndustries Works! Thanks for the implementation.
