### ISSUE TITLE
Schematic: Issue when placing part  

### ISSUE THREAD

**Issue by bohrh** [horizon-eda/horizon#356]
When placing resistors (not tested with other parts) onto an net-line the net is cut with crossed ends.
When rotating the part by 180°  it is correct again. But when copying again the issue show up again.

See attached screenshots

![Screenshot_20200323_210718](https://user-images.githubusercontent.com/37756573/77360953-9d2bee00-6d4e-11ea-9ca2-a26b412b93c9.png)

![Screenshot_20200323_211045](https://user-images.githubusercontent.com/37756573/77360961-a2893880-6d4e-11ea-84ad-6fe280f37fa9.png)

![Screenshot_20200323_211220](https://user-images.githubusercontent.com/37756573/77360971-a7e68300-6d4e-11ea-98d9-930e11b59bfa.png)

Horizon Version:
Commit 040bdc7a 2020-03-22 13:04:26 +0100 add context menu to recent items

**Comment by carrotIndustries** [comment]
Well, that was easy. No idea why I got this backwards. I remember this working as intended...
