### ISSUE TITLE
Cannot export pick and place file: Error Output file not opened

### ISSUE THREAD

**Issue by atoav** [horizon-eda/horizon#357]
I can't export a pick and place file for some reason.

In the file chooser dialogue I can only select a directory, while the window title clearly tells me to select a file:  
![pickandplace-window](https://user-images.githubusercontent.com/6620266/77466864-37516c00-6e0b-11ea-9eb0-b659c6ed9846.png)  

When I try to export it then tells me this:  
![pickandplace-error](https://user-images.githubusercontent.com/6620266/77466878-3c162000-6e0b-11ea-9b8b-76023bc15f5f.png)  

I tried all possible options and also tried entering a path manually, but nothing seems to work.

**Comment by carrotIndustries** [comment]
You didn't enter a filename for the top side, that's probably why. The title for the filechooser is set incorrectly, it indeed picks a directory.

**Comment by atoav** [comment]
> You didn't enter a filename for the top side

Spot on – That Error message mislead me

**Comment by carrotIndustries** [comment]
24281f3b3b19965507e7ec6c3285a79f8cb3854a fixes the filechooser's title

**Comment by atoav** [comment]
> we should probably deactivate the export button until all entries are filled in

Excellent idea : )

**Comment by carrotIndustries** [comment]
> we should probably deactivate the export button until all entries are filled in

done in eb2698bb55bff8605d53eeb6ea97b7e5e86e4f7f. The subsequent commits did the same for all other export windows.

**Comment by atoav** [comment]
Thank you very much
