### ISSUE TITLE
Question: KiCad Import

### ISSUE THREAD

**Issue by greenscreenflicker** [horizon-eda/horizon#359]
I have a heritage in KiCad and thinking to switch to horizon-eda, as DRC is far better here for high voltage issues. (And feature requests are actively listened to...)

To avoid a redesign of a current project, is there any possibility to import KiCAD projects? I think It could be nice, to start with the schematic. Are there any intentions to do that? I would understand if that would be too much work... So feel free to close.

**Comment by carrotIndustries** [comment]
> Are there any intentions to do that?

No, since that would require importing library items as well which isn't easily possible in an automated fashion due to vastly different concepts. Also, this would take too much time that's better spent elsewhere.
