### ISSUE TITLE
Error while loading shared libraries

### ISSUE THREAD

**Issue by trembel** [horizon-eda/horizon#373]
On starting horizon-eda I got the error code `horizon-eda: error while loading shared libraries: libgit2.so.28: cannot open shared object file: No such file or directory`

My setup:
- 5.4.28-1-MANJARO
- aur/horizon-eda 1.0.0-1 (+0 0.00%) (Installed)
- extra/libgit2 1:0.99.0-3 (611.0 KiB 1.8 MiB) (Installed)

**Comment by carrotIndustries** [comment]
This usually happens if libgit2 got upgraded after installing horizon-eda. You'll need to rebuild/reinstall horizon-eda to have it link against the new version of libgit2.
