### ISSUE TITLE
Scrolling can accidentally change values in Unit and Entity editors

### ISSUE THREAD

**Issue by Timmmm** [horizon-eda/horizon#393]
Thought I'd better start making separate issues rather than adding to #390!

If you scroll with the mouse wheel and while scrolling the mouse happens to land on top of a dropdown or spinner control, then it will stop scrolling and instead change the control value. Took me a while to figure out how some of the swap groups had been changed to 1 or 2. Also an issue in the Unit Editor. In this gif I'm only using the scroll wheel:

![7lnqhxMqGt](https://user-images.githubusercontent.com/376842/81581591-d96ee880-93a6-11ea-80d7-1f951b99f3cc.gif)

**Comment by carrotIndustries** [comment]
Well, this is bit unfortunate since gtk works that way: https://gitlab.gnome.org/GNOME/gtk/-/issues/593

The best we could do is disable scrolling for the dropdowns and spinners.

**Comment by Timmmm** [comment]
> The best we could do is disable scrolling for the dropdowns and spinners.

Yeah I think that is the most reasonable workaround.

**Comment by Timmmm** [comment]
Nice one!
