### ISSUE TITLE
Incompatible Alternate Package - Errors only at Board Layout

### ISSUE THREAD

**Issue by saagraa** [horizon-eda/horizon#397]
Packages with different number of mechanical holes and the same number of electrical pads can be set as alternates in the pool. However, when you try to use the alternate in the board layout you get a "Incompatible alt package" error.

A workaround (or perhaps preferred?) is to define the extra mechanical holes on the outline layer.

Should mechanical padstacks cause incompatible packages?

**Comment by carrotIndustries** [comment]
> Should mechanical padstacks cause incompatible packages?

No, the compatibility check is only there to prevent track connections from breaking when changing to an alternate package. Since we can't connect tracks to mechanical pads, they also shouldn't cause incompatibilities.
