### ISSUE TITLE
Option to switch layer when placing via during routing a track.

### ISSUE THREAD

**Issue by rroohhh** [horizon-eda/horizon#410]
And some way to select which layer to switch to (like the kicad layer pair thing).
Maybe even a layer pair setting per net / netclass?

**Comment by bob-u** [comment]
Probably the easiest way to add the feature would would be to have a key combination for layer selection.

**Comment by fruchti** [comment]
This would be indeed nice to have. For me, it has become second nature to hit `1` or `2` after placing a via but initially it was a bit weird for me, coming from KiCad.

> Probably the easiest way to add the feature would be to have a key combination for layer selection.

I thought about something similar: There could be a key binding for ‘place via’ and one for ‘place via and change layer’. A global setting for the via placement behaviour would be possible by reassigning the key binding. You could still invoke the current behaviour when you'd want to change to one layer explicitly (useful for multilayer boards) or stay on the same layer (for manual via stitching).

**Comment by bob-u** [comment]
How about a feature that flips to previous layer selection when routing and via is placed?   The first time you'd have to select layer manually, but the next time you'll be flipping between two layers automatically.  Or, revert to previous layer selection with 0 key.

right now:
r...v3...v1...v3...v1

with automatic flip to previous layer:
r...v3...v...v...v

with 0 to flip to previous layer:
r...v3...v0...v0...v0

**Comment by carrotIndustries** [comment]
The only reason why placing a via doesn't switch layers is that I was too lazy to figure out which layer to switch to on >2 layer boards.

My take on how to improve on this: Add a rule "layer pairs" that matches on a net (net, netclass, the usual stuff) and two layers. The usual rule resolution (first one that matches) will be used to find the layer to switch to.

**Comment by pwnorbitals** [comment]
This would be useful. Has a solution been implemented, or has it been dropped @carrotIndustries ?

**Comment by carrotIndustries** [comment]
It's implemented in the linked commit.
