### ISSUE TITLE
Ability to drag via

### ISSUE THREAD

**Issue by rroohhh** [horizon-eda/horizon#418]
Dragging the via should consider the design rules and automatically keep the connected tracks in multiple of 45 degrees orientation.

**Comment by carrotIndustries** [comment]
See branch `drag-via2` for where I added via dragging using the KiCad router. Doesn't work particularly well (springback doesn't work), but dragging vias in KiCad doesn't work any better either.

**Comment by rroohhh** [comment]
I played around a bit with it, and its definitely better than without the router.
