### ISSUE TITLE
pan_drag_warped does not work when panning to the right

### ISSUE THREAD

**Issue by bob-u** [horizon-eda/horizon#420]
Cursor movement wraps when panning past top, left and bottom border, however only sometimes when panning through right border.

EDIT: this issue only occurs when window is maximized. 

EDIT: here's more information:

While panning within maximized window, cursor is being blocked (temporarily) from going past get_allocated_width() which is the trigger for the wrap.

x > get_allocated_width()

pan_drag_begin 
3546: 3511.5 
3546: 3514.39 
3546: 3522.41 
3546: 3525.41 
3546: 3534.41 
3546: 3545.41 
3546: 3546 
3546: 3546 
3546: 3546 
3546: 3546 
3546: 3546 
3546: 3546 
3546: 3546 
3546: 3546 
3546: 3546 
3546: 3546 
3546: 3546 
3546: 3546 
3546: 3546 
3546: 3546.73 
3546: 8.03796 
pan_drag_warped 
3546: 11.038 
3546: 17.038 
3546: 20.038 

However, when there's a toolbar on the right side, such when component is selected, cursor goes past get_allocated_width() without a problem and warp works.  Similarly when window is minimized, it work as intended:

pan_drag_begin 
3140: 3105.39 
3140: 3106.33 
3140: 3107.57 
3140: 3110.87 
3140: 3114.73 
3140: 3115.47 
3140: 3116.82 
3140: 3121.92 
3140: 3125.75 
3140: 3130.22 
3140: 3140.22 
3140: 7.0426 
pan_drag_warped 
3140: 9.0531 
3140: 16.0531 
3140: 17.0531 
3140: 24.0398 

EDIT:  if panning slowly - warp works, panning fast cursor stops at get_allocated_width().

**Comment by carrotIndustries** [comment]
Thanks for figuring out the exact circumstances that caused this bug.

**Comment by bob-u** [comment]
Happy to help.  I learn a little about the program from the commits - so thank you for bothering with the descriptions.  I know not everyone does it.
