### ISSUE TITLE
Feature request: keyboard shortcuts for setting visibility of all layers

### ISSUE THREAD

**Issue by jue89** [horizon-eda/horizon#426]
I like to go through all layers one-by-one for a final check of boards and packages.
To achieve this, I disable the visibility of all layers by clicking all the eye icons and then step through them with the arrow keys. The highlighted layers becomes visible temporary.

Changing the visibility of all layers is a tedious mouse-driven task.

It would help to have keyboard shortcuts to:
* disable the visibility of all layers
* enable the visibility of all layers

**Comment by carrotIndustries** [comment]
I think I have a better way to address this issue: Add some kind of dropdown menu to the layer box on the left with these options
 - Display layers as-is
 - Work (selected) layer only
 - Shadow other layers (similar to kicad's high contrast mode)

If desired, we can add actions for these options so that they're reachable using shortcuts.

**Comment by jue89** [comment]
> I think I have a better way to address this issue: Add some kind of dropdown menu to the layer box on the left with these options
> 
>  - Display layers as-is
> 
>  - Work (selected) layer only
> 
>  - Shadow other layers (similar to kicad's high contrast mode)
> 
> 
> 
> If desired, we can add actions for these options so that they're reachable using shortcuts.

Sounds great :) Would love to see this feature in the future.

**Comment by bob-u** [comment]
On same topic, I would like to see pads more prominent - they get lost under copper color.

![Screenshot from 2020-06-16 10-07-13](https://user-images.githubusercontent.com/61708771/84786151-5c90e900-afba-11ea-9a98-5421a14a9c37.png)

![Screenshot from 2020-06-16 10-07-52](https://user-images.githubusercontent.com/61708771/84786172-61ee3380-afba-11ea-90cb-2dbeee15e3ec.png)

![Screenshot from 2020-06-16 10-11-24](https://user-images.githubusercontent.com/61708771/84786179-66b2e780-afba-11ea-9c69-b763cbb0d82c.png)

**Comment by bob-u** [comment]
![ShadowTraces](https://user-images.githubusercontent.com/61708771/85212457-fe993400-b320-11ea-9970-4a323d84db57.png)

Looks good.  Are you planning to add keyboard shortcuts at later timet?

**Comment by jue89** [comment]
Love it. Great work, @carrotIndustries!
