### ISSUE TITLE
RenderDoc reports Incorrect API Use

### ISSUE THREAD

**Issue by bob-u** [horizon-eda/horizon#432]
Output from RenderDoc and latest build (1.1.1 also has errors):

![RenderDoc_EDA_Errors](https://user-images.githubusercontent.com/61708771/85178905-a2b1ab00-b24d-11ea-880d-335b7ad9f9c1.png)

**Comment by carrotIndustries** [comment]
Unfortunately, renderdoc doesn't appear to work on my system. Opening the capture fails with " replaying the capture failed at api level".

**Comment by bob-u** [comment]
Moved to discourse
