### ISSUE TITLE
Schematic grid setting is 'grayed out'

### ISSUE THREAD

**Issue by bob-u** [horizon-eda/horizon#437]
Schematic's grid dimensions cannot be changed:

![grid_grayed_out](https://user-images.githubusercontent.com/61708771/85425601-603ae780-b547-11ea-82ee-74b83be1236d.png)

**Comment by carrotIndustries** [comment]
This is intended behaviour since the schematic's grid has to match the pin grid of the symbols in the pool. Changing the grid will lead to people messing up their schematics and cause even more issues.

**Comment by katyo** [comment]
@carrotIndustries But the ability to change grid still matter for symbol editing.

**Comment by carrotIndustries** [comment]
> But the ability to change grid still matter for symbol editing.

Why? with a user-definable grid users might wind up placing pins off-grid. If you need a finer grid for drawing the symbol itself, you can always switch to the fine grid by pressing alt/ctrl.

**Comment by rapgenic** [comment]
What about using a fully custom library with a custom pin to pin spacing? 

For example, in my use case I want to design my own library, and for stilistic (historic) reasons I'd use a 100mil grid for both the library and the schematic.
