### ISSUE TITLE
No microSD card in cardreader causes error popup on launch

### ISSUE THREAD

**Issue by VasiliSker** [horizon-eda/horizon#439]
I have win 7 empty USB card reader connected, when launched Horizon it pops 'no drive' error, and keep showing it no matter what i click (ignore/continue/repeat)
That was first launch (fresh installed)

**Comment by bob-u** [comment]
Take a look at: https://www.easeus.com/partition-manager-software/fix-no-disk-in-drive-error.html#3

Try fix 3 or 6.

**Comment by VasiliSker** [comment]
thanks, 6 should work but i would suggest to not spam all hard drives with requests that will cause that

**Comment by bob-u** [comment]
Certainly.  I just posted a workaround so it does not stop you or someone else from exploring the software until it's fixed.

**Comment by carrotIndustries** [comment]
Hm, interesting. I guess this a Gtk issue. Unfortunately, I can't reproduce this issue. What does sysinternals procmon show for horizon-eda.exe?

**Comment by bob-u** [comment]
Something similar is discussed here: https://github.com/Beep6581/RawTherapee/issues/3544

**Comment by carrotIndustries** [comment]
Try https://ci.appveyor.com/project/carrotIndustries/horizon/builds/33727952 once the build has finished and see if it fixes your issue.

**Comment by VasiliSker** [comment]
sorry cant reproduce after setup. Happened only on first launch

**Comment by bob-u** [comment]
> I have win 7 empty USB card reader connected, when launched Horizon it pops 'no drive' error, and keep showing it no matter what i click (ignore/continue/repeat)

> sorry cant reproduce after setup. Happened only on first launch

Was the fix to just restart the app and issue went away w/o making changes?

**Comment by VasiliSker** [comment]
Applied fix from comment 2, launched horizon and downloaded tools, after that it works even if fix deleted. also at first start it showed some different intro screen

**Comment by VasiliSker** [comment]
Fix works, no errors pops out.
