### ISSUE TITLE
Search only matches beginning of word

### ISSUE THREAD

**Issue by rroohhh** [horizon-eda/horizon#445]
Searching in one of the many lists only matches the beginning of the list items. Some way to match arbitrary parts would be nice.

**Comment by carrotIndustries** [comment]
You're referring to the typeahed search in treeviews? That's provided by gtk and users might expect that it does prefix match.
In which places would you consider regular matching the better option?

**Comment by rroohhh** [comment]
The keybindings list in the preferences windows and the `select net` window would be two examples that come to mind.

**Comment by carrotIndustries** [comment]
Use the branch above, apply `tree_view_set_search_contains` wherever you see it and open a PR.

**Comment by rroohhh** [comment]
Will do
