### ISSUE TITLE
Issue: cursor vs mouse pointer

### ISSUE THREAD

**Issue by bob-u** [horizon-eda/horizon#448]
As I was taking screenshots to illustrate selection list I noticed that when cursor snaps to an object near the mouse pointer and LMB is pressed coordinates are taken from the mouse pointer location instead of cursor location.  I would expect that Cursor location would take precedence or at least snapped to object would be on the list to select?

![selection_list2](https://user-images.githubusercontent.com/61708771/86241740-7c570e00-bb71-11ea-8d58-c8c94cee9692.png)

EDIT: I do see how getting mouse pointer position is a better option.  Given sometimes (seemingly) random cursor moves what is the purpose of the cursor when no tool is selected?

EDIT2: ok, I see cursor moves are not 'random' as I described above only that it tries to snap to ALL of the objects AND the grid in tool-less mode.  Green cursor snaps to grid, changes to red when it snaps to an object.

EDIT3: I replaced all SelectionMode::NORMAL instances with SelectionMode::HOVER and I like this as default much better. Now  I have to figure out how to switch Horizon to click select mode when multiple objects are selected.

**Comment by bob-u** [comment]
`bool ImpBase::handle_click_release(GdkEventButton *button_event)
{
    if (button_event->button == 3) {canvas->set_selection_mode(CanvasGL::SelectionMode::HOVER);} // revert to hover select with left click
I think I like the behavior where RMB reverts back to hover mode, below.  For this to work perfectly hover selection would have to look different from actual selection.

    if (core->tool_is_active() && button_event->button != 2 && !(button_event->state & Gdk::SHIFT_MASK)) {
        ToolArgs args;
        args.type = ToolEventType::CLICK_RELEASE;
        args.coords = canvas->get_cursor_pos();
        args.button = button_event->button;
        args.target = canvas->get_current_target();
        args.work_layer = canvas->property_work_layer();
        ToolResponse r = core->tool_update(args);
        tool_process(r);
    }
    return false;
}`

**Comment by carrotIndustries** [comment]
> I do see how getting mouse pointer position is a better option. 

Yes, snapping box selection to the grid is really pointless and annoying. (looking at you, kicad schematic editor)

> what is the purpose of the cursor when no tool is selected?

Some tools such as move use the cursor location as a starting point since snapping to things before doing the move is really useful in some cases.

**Comment by bob-u** [comment]
Moved to discourse
