### ISSUE TITLE
Junction in via

### ISSUE THREAD

**Issue by bob-u** [horizon-eda/horizon#449]
What is the purpose of junction in via?  Why is it selectable, can be duplicated, moved and copied apart from via itself?

**Comment by carrotIndustries** [comment]
Because that's how it works internally: Tracks start/end at junctions (or pads) and vias are attached to junctions. Junctions are regular objects such as tracks and vias.

**Comment by bob-u** [comment]
If there there's no valid task to be done with via's junction, then shouldn't selecting via's junction select via or via and junction (i.e. there's no point in selecting junction alone)?

**Comment by bob-u** [comment]
I see that important tool operations selected for junction are applied to via+junction and only few menu items are available but do not do anything.  I am closing this ticket as this is quite minor issue in the scheme of things.

Perhaps one more improvement I could suggest would be for HUD to display via information when junction is selected, after-all no one want's to know more information or do operations on junction alone.
