### ISSUE TITLE
Swap Group "invisible" on selected pin

### ISSUE THREAD

**Issue by trembel** [horizon-eda/horizon#459]
When a Pin is selected in the Unit Editor, the text of the swap group field seems invisible/white (see figure).
[
![unit_editor](https://user-images.githubusercontent.com/28383252/87409197-ec7b8000-c5c4-11ea-9e57-88f8201a7df0.png)
](url)

System:
```
Linux 5.4.44-1-MANJARO #1 SMP PREEMPT Wed Jun 3 14:48:07 UTC 2020 x86_64 GNU/Linux
aur/horizon-eda 1.1.1-1 (+2 0.77%) (Installed)
    free EDA package written in C++
```

**Comment by carrotIndustries** [comment]
This is probably your theme being broken. Try with the adwaita theme. Also see https://blogs.gnome.org/tbernard/2018/10/15/restyling-apps-at-scale/
