### ISSUE TITLE
How do I add a 3D model to a part?

### ISSUE THREAD

**Issue by bob-u** [horizon-eda/horizon#466]
How do I add a 3D model to a part?

![3dModel](https://user-images.githubusercontent.com/61708771/87887245-534bcf80-c9f1-11ea-8f2d-9ae5db21a52f.png)

**Comment by carrotIndustries** [comment]
Don't open issues for "how do I questions: https://blog.horizon-eda.org/comments/ Post to one of the forum threads or join the IRC channel.
