### ISSUE TITLE
Feature request: part generator: ability to suppress pads

### ISSUE THREAD

**Issue by bob-u** [horizon-eda/horizon#470]
Some IC do not use all of the pads in given standard package.  It would be nice to be able to suppress generation of certain pads in the standard package so pad numbers come up correctly and there is no need to manually delete them.  And/or have ability to renumber selected pads (currently all pads get renamed to the same name).

![wrong_pad_numbers](https://user-images.githubusercontent.com/61708771/88120138-3d284580-cb90-11ea-88d2-f8f6e7c1f9cc.png)

![TMC5160](https://user-images.githubusercontent.com/61708771/88120248-7e205a00-cb90-11ea-99a5-4dd9ca592451.png)

**Comment by carrotIndustries** [comment]
> and/or have ability to renumber selected pads 

Select the pads you want to renumber and use the "renumber pads" tool.

>  so pad numbers come up correctly

The pad numbers in your screenshot are most likely correct. All packages I've seen that are missing pins from a standard package usually keep its pin numbering.

**Comment by bob-u** [comment]
As you can see on dimensional drawing for the part - pads are actually numbered as they are.  The IC is TMC5160.  

Renumber pads tool is great.  Thanks.
