### ISSUE TITLE
Feature request: ability to apply pad properties in bulk

### ISSUE THREAD

**Issue by bob-u** [horizon-eda/horizon#474]
Feature request: ability to apply pad properties to selected pads.  Currently properties can only be applied one pad at a time:

![edit_padstack0](https://user-images.githubusercontent.com/61708771/88123333-ae6bf680-cb98-11ea-9b9e-a728c4153780.png)

![edit_padstack](https://user-images.githubusercontent.com/61708771/88123337-b1ff7d80-cb98-11ea-9a24-dc818f5815f2.png)

**Comment by rroohhh** [comment]
If you press the checkmark they get applied to every pad.

**Comment by bob-u** [comment]
Lol, it did not occur to me that this button was for that ( I thought it was to apply the individual parameter).  I would suggest to make this button 'All' to follow the convention, as in the right hand menu.

Speaking of apply - it would be nice to have an apply button (or changes made in real-time) so one can see the changes  them w/o exiting the window.  Especially since it's possible to select individual pads with the selector within the window.

**Comment by atoav** [comment]
> Speaking of apply - it would be nice to have an apply button (or changes made in real-time) so one can see the changes them w/o exiting the window. Especially since it's possible to select individual pads with the selector within the window.

If there are performance worries this could be a checkbox like in Photoshop filters: `[ ] Preview`

As for the apply to all button, I could imagine `All` or a double checkmark `✓✓` (maybe a bit closer together in terms of kerning, but there is no UTF-8 Symbol for that)
