### ISSUE TITLE
What are the rules on assigning key sequences to tools?

### ISSUE THREAD

**Issue by bob-u** [horizon-eda/horizon#482]
What are the rules on assigning key sequences to tools/features?  I tried to assign 'vs' to turn off snapping in schematic and feature is triggered by just pressing v alone.

**Comment by carrotIndustries** [comment]
Key sequences are recognized as soon as they aren't ambiguous. As you probably don't have any other key sequence configured that starts with <kbd>v</kbd>, the first key is sufficient.

**Comment by bob-u** [comment]
It appears that key assignment needs sanitization.  Here's an example where I assign ppp to draw polygon circle.  Unfortunately pp is already taken to place part.  Once ppp is entered - neither function works:

![key_not_working](https://user-images.githubusercontent.com/61708771/89089872-6eadc780-d36d-11ea-80d3-dd00249be2bb.gif)

**Comment by carrotIndustries** [comment]
Unfortunately, it's not really feasible to detect this when defining the key sequence as we can't tell a this point if key seqeuences could conflict.

The best we could come up with is informing the user about conflicting key sequences as they're being entered in the editor.

**Comment by atoav** [comment]
> The best we could come up with is informing the user about conflicting key sequences as they're being entered in the editor.

This should give you two options:
- _Abort_ the operation
- _Unset_ the (other) conflicting key/value pair and _set_ this one

Ideally the latter option would also give you the ability to quickly change the other/conflicting shortcut afterwards, but this is a comfort nearly no software I ever used offers.
