### ISSUE TITLE
Recovering messed up pool

### ISSUE THREAD

**Issue by cyclic99** [horizon-eda/horizon#494]
Is there a way to sort out a mess-up in my pool i.e. resync from github without needing a start again with empty directory?
Weekend ~2 weeks ago some many parts spontaneously disappeared - cpl, samsung, panasonic resistors + own created O&S
The resistor selector function also disappeared.
I do not know how it was caused
I can download a new pool and all is there
but I seek to recover the situation not start again from scratch
Was at 1.1.0 then - now at 1.2.0 Kubuntu 20.04

**Comment by carrotIndustries** [comment]
Please start a topic on https://horizon-eda.discourse.group/ Issues aren't for user support.
