### ISSUE TITLE
Temporary finer grid not working when routing tracks

### ISSUE THREAD

**Issue by pipatron** [horizon-eda/horizon#498]
Normally you can hold _Alt_ when moving the cursor to temporarily get a finer grid. This does not appear to work when routing.

Perhaps not very important, but I just ran into a situation where it would have been useful.

**Comment by carrotIndustries** [comment]
Yes, this is a know deficiency as the router does its own grid/snapping handling and I haven't yet figured out a non-hacky way to make it work.
