### ISSUE TITLE
Duplicate net label warning/block rule

### ISSUE THREAD

**Issue by cyclic99** [horizon-eda/horizon#500]
When trying to use net labelling to connect distant (on schematic) nets without the clutter of net lines it accepts the multiple net name placements and they even appear on the components on board however it complains with a "duplicate net name" red triangle and and only puts up wire to the first instance e.g. to a via.
The other instances are there on the board but cannot be routed.
Is there a deliberate rule preventing this?  I cannot see one yet it seems forbidden.
Can it be done another way? I.e. Am I missing something?
Else can it switchable on/off as a rule.

**Comment by carrotIndustries** [comment]
You've created two nets and renamed them to have the same name. To merge them / change connectivity, use the "move net segment to other net" tool. 

Before opening an issue the next time, start a topic on https://horizon-eda.discourse.group/
