### ISSUE TITLE
Usability: autoselect item under mouse for certain actions

### ISSUE THREAD

**Issue by anuejn** [horizon-eda/horizon#504]
Hey,
for certain actions (in my case mostly "drag track / via") it would be nice to have the action autoselect the first item under the mouse. Then one would only press the keybinding to triger that action even when nothing is selected.
That would bring a big speedup to my routing workflow :).

**Comment by carrotIndustries** [comment]
Isn't that what hover select is for?

**Comment by bob-u** [comment]
As a new user I also was confused why hover mode disappeared once selection was made.  It is not obvious, but you can go back to hover mode by pressing escape key.

**Comment by anuejn** [comment]
yup i am thumb :(.
sorry for the noise
