### ISSUE TITLE
'Save changes before closing' does not actually save if in routing mode

### ISSUE THREAD

**Issue by pipatron** [horizon-eda/horizon#505]
Steps to reproduce:
1. Open a PCB in the board editor.
2. Move a component or do some non-routing related and obviously visible change.
3. Route a track, but do _not_ exit the routing mode.
4. Close the PCB editor (Click the X in the corner if you have one, _Alt-F4_ etc)
5. The requester pops up asking you to save changes before closing. Press **Save**.

The change made in step 2 is not saved, even though everything appears to work.

It sounds like an unlikely scenario, but since it is not obvious that you remain in routing mode after completing a track, this has happened to me at least once by mistake.

Maybe it's possible to to force-exit whatever tool you're in before exiting?

**Comment by carrotIndustries** [comment]
> Maybe it's possible to to force-exit whatever tool you're in before exiting?

That's exactly what's done now. This however doesn't work if the tool uses a modal dialog and the save is triggered by closing the project manager as it's not really feasible to forcibly end these tools.
