### ISSUE TITLE
Unable to increase mask for mechanical hole

### ISSUE THREAD

**Issue by cyclic99** [horizon-eda/horizon#506]
I have to have bare board around mechanical fixing holes, top and bottom.

In pool I created duplicate of padstack circular
 mechanical hole --> 2.75mm (M2.5)
I edit new duplicate to be 2.75 diameter hole and set mask plus 1.375mm
I save and the correct image hole & mask is displayed in the pool padstack tab
I update pool and refresh cache 
On board I places mechanical holes 2.75mm and they appear ok including increased mask
On exit place hole command, the hole size stays at 2.75mm but mask reverts to only plus 0.05mm
gerber files are the same
I see no preference for mask plus delta but default 0.05mm is ok
I see no way of overriding the default 0.05
Rules check overall show 0.05mm mask plus delta which is ok
I can add a parameter at the board level but appears not to have any effect on mask either
I have also made complete restart of horizon-eda (necessary for some changes) but no change.

Photos: pool and board
[horizon-eda_horizon-eda_Issue-hole-mask_@800.zip](https://github.com/horizon-eda/horizon/files/5144958/horizon-eda_horizon-eda_Issue-hole-mask_%40800.zip)

**Comment by carrotIndustries** [comment]
> I have to have bare board around mechanical fixing holes, top and bottom.

That question is usage-related, unlikely to be a bug. Please start a thread on https://horizon-eda.discourse.group/ and attach proper screenshots.
