### ISSUE TITLE
"Miter" and "Square" types for planes are swapped

### ISSUE THREAD

**Issue by pipatron** [horizon-eda/horizon#507]
World's smallest issue but still:

Planes can have a style: _Round_, _Square_, and _Miter_. For some reason, _Square_ and _Miter_ does the opposite of each other. It doesn't matter if I make the plane use the global rules or its own unique rule — they still do the opposite of what it says.

I thought it would be simple enough that even I could find the problem in the source code, but everything _seemed_ to be in the right order and connected to the right buttons.

**Comment by carrotIndustries** [comment]
IIRC someone else also noted this a while back. The Plane style maps directly to clipper's join type: http://www.angusj.com/delphi/clipper/documentation/Docs/Units/ClipperLib/Types/JoinType.htm Does this match what you're seeing?

**Comment by pipatron** [comment]
Indeed, that's the same behavior. By the author's use of quotes around the word _square_ I think they also didn't think it made much sense. I don't think you could find anyone who thinks this trivial example is intuitive:

![screenshot](https://user-images.githubusercontent.com/14086495/91898613-45e65e00-ec9c-11ea-90f4-0cc284f7e17f.png)

Maybe the solution is to rename _Square_🡒_Bevel_ and _Miter_🡒_Sharp_ or something similar.

**Comment by fruchti** [comment]
> IIRC someone else also noted this a while back.

That might've been me on IRC. I'm still for changing the naming here.

> Maybe the solution is to rename _Square_ 🡒 _Bevel_ and _Miter_ 🡒 _Sharp_ or something similar.

Sounds way better that way to me.
