### ISSUE TITLE
Flatpak package: outdated Gnome runtime 

### ISSUE THREAD

**Issue by acisternino** [horizon-eda/horizon#508]
Not overly important but when I updated my flatpak packages I got this message:

```
Info: org.gnome.Platform is end-of-life, with reason: The GNOME 3.34 runtime is no longer supported as of 14th August 2020. Please ask your application developer to migrate to a supported platform.
```

A bit of investigation showed me that it's Horizon EDA that uses 3.34.

Thanks for the awesome program (and the flatpak distribution!).

**Comment by carrotIndustries** [comment]
See if https://github.com/flathub/org.horizon_eda.HorizonEDA/pull/1#issuecomment-691487880 works.

**Comment by acisternino** [comment]
Thanks for the quick update!  
Seems to work fine for me.
