### ISSUE TITLE
Local environment information leaks in board.json

### ISSUE THREAD

**Issue by ellenhp** [horizon-eda/horizon#512]
Hey! I'm trying to check in a Horizon project and I'm having some issues with local environment information being leaked into the version controlled files. In board.json I notice this:

`        "output_directory": "/home/ellen/horizon/project",`

I'm wondering how hard it would be to move that to something I could gitignore. I know you did this with impl_meta files not too long ago so I figure you may have just missed a field? Anyway, thanks for this software it's been really nice to use :)

**Comment by carrotIndustries** [comment]
If the output directory is a subdirectory of the project (though not the project directory itself), it should automatically get translated into a project-relative path.

**Comment by ellenhp** [comment]
That makes sense and works perfectly. Thank you!
