### ISSUE TITLE
Footprint editor, Layer mode - "work layer only" - unable to select end points

### ISSUE THREAD

**Issue by Pitrsek** [horizon-eda/horizon#518]
Hello,
when is work layer mode set to work layer only, I'm unable to select anchor points of silk screen, only the whole lines/arcs. If I switch to "As is", I can select end points/anchor points. I believe end points/anchor points should be selectable in work layer only mode as well.

Cheers,
Pitrsek

**Comment by carrotIndustries** [comment]
Good catch, that very issue got fixed for boards a while back, but didn't make it into the package editor.
