### ISSUE TITLE
exception thrown in tool_begin of Route track

### ISSUE THREAD

**Issue by Pitrsek** [horizon-eda/horizon#525]
I tried to route my board today and was greeted with:
Seq | Level   | Domain                  | Message; Detail
0   | Info    | Block                   | loading block b13c5a15-6c9d-497c-ba16-e2e4ea29bd03;  (startup)
1   | Info    | Board                   | loading board 993142f7-5358-40f3-b8a4-741661e0a8f3;  (startup)
2   | Critical| Core                    | exception thrown in tool_begin of Route track; invalid pad polygons: 0

Reboot did not helped, I haven't a slightest clue as to what has changed.To my knowledge my setup remained the same. Happens when i press x to route. 

Cheers,
Pitrsek

**Comment by Pitrsek** [comment]
I realized that I have updated a package footprint. When I delete it, routing works.

**Comment by carrotIndustries** [comment]
> When I delete it, routing works.

Please share that particular package so I can reproduce it.

**Comment by Pitrsek** [comment]
Here you go. 
[CP-40-7V2.zip](https://github.com/horizon-eda/horizon/files/5433203/CP-40-7V2.zip)
I think i know what is causing the issue - package contains pads that do not have copper layer. I used those to create the shape, instead of drawing with curves.

**Comment by carrotIndustries** [comment]
The zip missing the padstacks.

**Comment by Pitrsek** [comment]
I've zipped whole project(@ your mail), hopefully it will work as everything should be in project pool cache.

**Comment by carrotIndustries** [comment]
> I've zipped whole project(@ your mail), hopefully it will work as everything should be in project pool cache.

Haven't received anything yet.
