### ISSUE TITLE
Placing via on pad centre doesn't connect to pad

### ISSUE THREAD

**Issue by RX14** [horizon-eda/horizon#528]
When placing a via in a pad, you have to draw a trace to the pad centre or horizon thinks there's no connection. This is fine, but when placing a via directly on the centre of a pad, the track has to be zero length. I've worked around this by drawing 0.001mm traces to my vias in pads, but this isn't ideal.

I suggest either considering any via touching a pad in the same net to be connected - or alternatively, consider vias which are directly at the pad centre to be connected.

**Comment by carrotIndustries** [comment]
See if the `airwires-delaunator` branch makes a difference.

>I suggest either considering any via touching a pad in the same net to be connected

Unfortunately, we don't really know how a pad looks like before rendering it, so we'll have to live with the connection only being made by the via being exactly at the pad's origin.

**Comment by RX14** [comment]
> Unfortunately, we don't really know how a pad looks like before rendering it, so we'll have to live with the connection only being made by the via being exactly at the pad's origin.

I'm okay with this!

The "false" airwires are gone when I build with the `airwires-delaunator` branch, thanks a lot!

**Comment by RX14** [comment]
This still seems to fail actually, on more complex scenarios...

![poomf-linux-2020-11-23T12 51 06](https://user-images.githubusercontent.com/2788811/99964088-ac09eb00-2d8a-11eb-9af2-51902e548702.png)

Note airwires on GND pads on the right hand side and USB_D+

The B12 GND pad has figured itself out correctly though

**Comment by carrotIndustries** [comment]
Can you share a minimum working design to reproduce this?
