### ISSUE TITLE
TextBoxes Lag

### ISSUE THREAD

**Issue by viniciusmiguel** [horizon-eda/horizon#530]
On Windows 10 2004 Build 19041.572 the TextBoxes are presenting Lag between the keypress and visualization.

Tested with last release 1.3.0 on a clean installation.

**Comment by carrotIndustries** [comment]
Which ones exactly? Are you using an intel gpu? There've been reports about things not working optimally with them: https://github.com/horizon-eda/horizon/issues/513

**Comment by viniciusmiguel** [comment]
Intel Xeon E-2176M
64Gb RAM
NVIDIA Quadro P4200

All the text boxes.

**Comment by viniciusmiguel** [comment]
I disabled the internal integrated graphics and the lag disappeared.
I can confirm there is an issue with intel integrated graphics.

**Comment by carrotIndustries** [comment]
I manged to reproduce this in the gtk demo, let's see what happens: https://gitlab.gnome.org/GNOME/gtk/-/issues/3487

**Comment by carrotIndustries** [comment]
See https://github.com/horizon-eda/horizon/issues/513#issuecomment-749833082, this should also apply to your issue. Can you check if this workaround works on your system?

**Comment by carrotIndustries** [comment]
This issue has been resolved by shipping a patched build of gtk, further progress related to going back to upstream gtk is tracked in #539
