### ISSUE TITLE
Exception is thrown when I click on [Update PR]

### ISSUE THREAD

**Issue by jue89** [horizon-eda/horizon#531]
How to reproduce:

* I installed Horizon 1.3.0 using AUR.
* I removed existing ~/.config/horizon
* I removed existing ~/Documents/horizon-pool
* I started Horizon and downloaded the default pool
* I logged into my Github account using to Pool manager
* I took one of my PRs and clicked that "Update PR" button

That exception is shown:

![Screenshot from 2020-11-14 19-18-23](https://user-images.githubusercontent.com/6105784/99154193-3927b280-26ae-11eb-939d-a09c0c2691c0.png)

**Comment by jue89** [comment]
Well, after thinking about it ... it looks like, I need to add my fork to the remotes of the pool's git checkout?!

**Comment by carrotIndustries** [comment]
> Well, after thinking about it ... it looks like, I need to add my fork to the remotes of the pool's git checkout?!

Not you need to do it, but the pool manager needs to (which it does now).

When implementing the PR update thing, it must have slipped my mind that the user might have created the PR with another copy of the pool, so I assumed the branch and remote to be there.
