### ISSUE TITLE
Gl Error 1285 when trying to add 3D model

### ISSUE THREAD

**Issue by allderdicerobotics** [horizon-eda/horizon#532]
![Screenshot 2020-11-19 145929](https://user-images.githubusercontent.com/35245530/99717970-22030f00-2a78-11eb-889d-50dd5c64dfd6.png)

This happens whenever I try to add a 3D model.

This is the file I am using:
[User Library-VQFN-20 3x3 0_45mm v2.zip](https://github.com/horizon-eda/horizon/files/5569399/User.Library-VQFN-20.3x3.0_45mm.v2.zip)

Also, I have seen other posts saying this is an out of memory error. My system is running Windows 10, I have a Ryzen 9 3900x and an RTX 2080 Super if that matters.

**Comment by carrotIndustries** [comment]
I've had other people report the same error also on nvidia gpus on windows. Unfortunately, I haven't been able to reproduce this so far. Try https://ci.appveyor.com/project/carrotIndustries/horizon/builds/36411382 and post the error message. That should help pinpointing the bug.

**Comment by allderdicerobotics** [comment]
Well... the bug no longer occurs in that build. As far as I can tell step files import fine now.

**Comment by carrotIndustries** [comment]
> Well... the bug no longer occurs in that build. As far as I can tell step files import fine now.

Does that also apply to the latest builds from master?

**Comment by allderdicerobotics** [comment]
> 
> 
> > Well... the bug no longer occurs in that build. As far as I can tell step files import fine now.
> 
> Does that also apply to the latest builds from master?

Latest build from master is good too! No more error. Thank you!

**Comment by carrotIndustries** [comment]
I have a feeling that we're onto something similar to #550
