### ISSUE TITLE
Duplicate part with new package triggers: Pool update errors: Package <x> not found

### ISSUE THREAD

**Issue by bsilver8192** [horizon-eda/horizon#535]
Looks like there's a problem with the order of operations when duplicating a part and creating a new package at the same time. Maybe there's a premature library update before the new package's file has been created?

Steps:
1. From the pool manager, select a part and click Duplicate Part
2. Leave the checkbox next to Package selected
3. Deselect the checkbox next to Entity (I haven't tried leaving that selected)
4. Fill in the filenames
5. Click "Duplicate"

This error pops up:
![Screenshot_2020-11-29_22-32-46](https://user-images.githubusercontent.com/2999225/100576366-dc71ed80-3292-11eb-8c75-bccbbef5151f.png)

Closing the error window and doing "Update pool" seems to make everything work correctly.

It happened every time I tried it.

I'm using version 1.3.0, installed via flatpak.

**Comment by carrotIndustries** [comment]
Good catch and thanks for the clear steps on reproducing this bug.
