### ISSUE TITLE
Move tool snap to diagonal option

### ISSUE THREAD

**Issue by RX14** [horizon-eda/horizon#538]
It would be nice to be able to snap to 45 degrees for moving things with the "m" tool, like you can already snap to horizontal, vertical with "/". Very useful for modifying pour boundaries which are often at diagonals.

**Comment by carrotIndustries** [comment]
What a coincidence, I just finished 084ac072a957ca779e38421b6d437e4438a54d11. Does this satisfy your needs?

**Comment by RX14** [comment]
I tried it out and it's perfect, just forgot to close this issue :)
