### ISSUE TITLE
Crash on selection when not using box  (Windows)

### ISSUE THREAD

**Issue by jpleger** [horizon-eda/horizon#550]
## Summary:
I noticed that the process will crash when you select any tool other than the box selection... For example, when I select lasso or paint, the process will crash as soon as I click on the blue canvas.

## How to Reproduce: 

1. Open a schematic
2. Select anything but the box for selection, for example:

![image](https://user-images.githubusercontent.com/2197150/104981541-09ef3380-59c6-11eb-8b88-1d0aa2559e1b.png)

3. Start selection on schematic
4. (crash)

### Windows Version

![image](https://user-images.githubusercontent.com/2197150/104981632-386d0e80-59c6-11eb-80f4-e40c0940ba59.png)

### Error from app

![image](https://user-images.githubusercontent.com/2197150/104982045-0ad49500-59c7-11eb-862e-50ab166e785a.png)

### Log file (stderr)
```
[C:\VCS\sot23_breakout\horizon\sot23_breakout\top_sch.json] (horizon-eda:22572): GLib-GIO-WARNING **: 19:43:15.245: win32 session dbus binary not found: C:\Program Files\Horizon EDA\\gdbus.exe
[C:\VCS\sot23_breakout\horizon\sot23_breakout\top_sch.json] (horizon-eda:11132): GLib-GIO-WARNING **: 19:43:23.953: win32 session dbus binary not found: C:\Program Files\Horizon EDA\\gdbus.exe
```

Based on the logs, this looks like a similar issue that was in inkscape where gdbus wasn't being built: https://gitlab.com/inkscape/inkscape/-/issues/482

**Comment by carrotIndustries** [comment]
This is very unlikely due to gdbus. Which Horizon version are you using?

**Comment by jpleger** [comment]
Running the most current version, 1.3.0.

I can try removing, purging registry keys, etc. or run in debug mode, not sure the best way to troubleshoot since I am not familiar with the codebase :(

**Comment by carrotIndustries** [comment]
Can you also try all other editors, i.e. package, frame, padstack etc. to see if the issue also occurs there. You can also try the latest build at https://ci.appveyor.com/project/carrotIndustries/horizon/builds/37326734/artifacts

**Comment by jpleger** [comment]
I just tested and it does the same thing in the other editors.

```
[C:\VCS\electronic-parts\padstacks\padstack.json] (horizon-eda:24008): GLib-GIO-WARNING **: 16:22:26.617: win32 session dbus binary not found: C:\Program Files\Horizon EDA\\gdbus.exe
```

Using the latest build, it also appears to have the same behavior.

![image](https://user-images.githubusercontent.com/2197150/105106536-52b0f600-5a73-11eb-9c8f-96052a35275b.png)

Log from stderr:

```
[C:\VCS\sot23_breakout\horizon\sot23_breakout\top_sch.json] (horizon-eda:8940): GLib-GIO-WARNING **: 16:25:53.275: win32 session dbus binary not found: C:\Users\jpleger\Downloads\horizon-2021-01-18-2252\horizon\\gdbus.exe
```

**Comment by carrotIndustries** [comment]
Getting a stacktrace on windows isn't exactly easy as that'll involve building from source https://docs.horizon-eda.org/en/latest/build-win32.html and starting the editor with gdb attached. If you want, I can try and walk you through the process.

What's your GPU vendor? Can you reproduce this on another system?

**Comment by jpleger** [comment]
Sorry, this is my Windows box so i'll need to setup a build environment, but that shouldn't be a big deal.

GPU is Nvidia 1080 card, I'll try to reproduce on another system here shortly.

**Comment by jpleger** [comment]
Tested on another box with the most recent build...

Had slightly different behavior, on first try when I edited a default padstack it worked... then I closed, reopened and edited a padstack again and it popped up a different error.

![image](https://user-images.githubusercontent.com/2197150/105110328-9a3b8000-5a7b-11eb-83fb-0a6d7a027aa8.png)

Similar error about session dbus binary not found:

```
[C:\Users\jen.HOME\Documents\horizon-pool\packages\manufacturer\intel\EQFP-144\padstacks\pad.json] (horizon-eda:3224): GLib-GIO-WARNING **: 17:02:18.785: win32 session dbus binary not found: C:\Users\jen.HOME\Downloads\horizon-2021-01-18-2252\horizon\\gdbus.exe
```

Its a slightly different windows build:
![image](https://user-images.githubusercontent.com/2197150/105110749-8c3a2f00-5a7c-11eb-89eb-3d1ff4ab261e.png)

**Comment by carrotIndustries** [comment]
Good news, I managed to reproduce this on my windows test machine.

**Comment by jpleger** [comment]
Awesome! I tried to get a build environment setup on windows last night, but was having difficulty getting it up and running (apologies, I'm not super familiar with msys2 environments).

I was looking at procmon and nothing immediately jumped out at me, but I'll admit that I am not very proficient in GTK on windows.

**Comment by carrotIndustries** [comment]
Try https://github.com/horizon-eda/horizon/actions/runs/499863104 once the build has finished or compile the commit and confirm that this fixes the crash for you as well.

This only crashing on windows with nvidia drivers (didn't crash on intel) was pure chance, I'm glad you found it.

**Comment by jpleger** [comment]
Confirmed this worked! Thanks so much, sorry I couldn't help more with finding the issue, not super familiar with the codebase :(

**Comment by jpleger** [comment]
Sry, I didn't see if there was a PR that got merged, so will leave open.
