### ISSUE TITLE
Display check results in the Pool manager's Remote tab

### ISSUE THREAD

**Issue by jue89** [horizon-eda/horizon#553]
It would be handy to add a column in the "Items to be merged" list that displays whether all tests of the respective item has passed.

I've recently opened some PRs in the horizon-pool repo before all checks were green. That wouldn't have happend if a red mark was displayed along with the item.

**Comment by carrotIndustries** [comment]
To avoid mishaps like #554, I'll merge this into master after 1.4 has been released.

**Comment by jue89** [comment]
Oh, sweet! Just checked out your feature branch - that's exactly what I had in mind :)

**Comment by carrotIndustries** [comment]
a59498af1c46ed743646bc3830f7d3e54775c08e adds this for the git tab
