### ISSUE TITLE
Exception thrown in Symbol editor on current master

### ISSUE THREAD

**Issue by jue89** [horizon-eda/horizon#554]
Commit 1b32099ca1dfe4a4231dad197cccde9d084222aa introduces a bug.

When I try to edit a symbol in the Pool manager and the symbol has disabled the "Can expand" option, an exception is thrown:

```
terminate called after throwing an instance of 'std::logic_error'
  what():  can't expand
```

**Comment by carrotIndustries** [comment]
Probably a good reminder not to add features 5 days before the release....
