### ISSUE TITLE
Bounding box doesn't account for outline polygons on parts

### ISSUE THREAD

**Issue by jmgao** [horizon-eda/horizon#562]
I've got a part that has an entire board outline on it, because it seemed like the best approach (it's an M.2 card edge connector), and it looks like this confuses the bounding box calculation, which returns the default 20mm x 20mm box centered on the origin.

The actual user-visible misbehavior I saw from this was in PDF export, but I'm not sure if this gets used elsewhere.

**Comment by carrotIndustries** [comment]
> I've got a part that has an entire board outline on it,

Isn't this super-annoying with that huge selectable thing in the background?
