### ISSUE TITLE
Part import wizard - assign pins - show the package

### ISSUE THREAD

**Issue by MarSik** [horizon-eda/horizon#566]
The Assign pins screen of the Part import wizard requires me to enter pin names for each numbered pad. However I cannot double check which pad is which.

This is an issue any time the footprint is either not an industry standard or where vendors use different numbering in the datasheets. Think about BCE, ECB ordering of TO92 transistors or the same issue in SOT23, TO220 and other packages.

**Comment by carrotIndustries** [comment]
How should the package preview show up? As an extra window that can be opened from the part wizard?

**Comment by MarSik** [comment]
What about a side bar of the dialog (same window)? Would that work?

**Comment by carrotIndustries** [comment]
This how it how it now looks like:
![2021-02-09-205930_1248x663_scrot](https://user-images.githubusercontent.com/877304/107420928-b9c54600-6b19-11eb-8610-14e58a2c4e2c.png)

**Comment by MarSik** [comment]
This ia great! Thanks.
