### ISSUE TITLE
Feature request: Board rules -> regex for net class names

### ISSUE THREAD

**Issue by jue89** [horizon-eda/horizon#578]
I've created a board with 3 different galvanically isolated zones. Each zone has two own net classes for power and signal - resulting in 6 net classes:
- A_signal
- A_power
- B_signal
- B_power
- C_signal
- C_power

A regex match for net classes would allow to formulate these rules:
- `signal$`: default track width 150um
- `power$`: default track width 500um
- `^A` -> `^[^A]`: min. copper clearance 5mm
- `^B` -> `^[^B]`: min. copper clearance 5mm
- `^C` -> `^[^C]`: min. copper clearance 5mm

The last three rules are not very readable - to be honest. Maybe the 2nd Match could get another option that matches every other entity not matching the 1st Match?

**Comment by carrotIndustries** [comment]
see the linked branch for the requested feature

**Comment by jue89** [comment]
Wow! Really nice! Just tried out my described use case and it looks great :)

![Screenshot from 2021-03-07 17-07-03](https://user-images.githubusercontent.com/6105784/110246399-bd58bb00-7f67-11eb-9c78-7efa495f0c18.png)
