### ISSUE TITLE
Option to disable dragging components

### ISSUE THREAD

**Issue by RX14** [horizon-eda/horizon#582]
I find often I end up accidentally dragging components when I'm trying to drag a box selection. I'd prefer to have the option to never drag components, like there's already an option to disable dragging to start tracks.

**Comment by carrotIndustries** [comment]
Should this be a global setting that applies to dragging in general in all editors?

**Comment by RX14** [comment]
yes please

**Comment by RX14** [comment]
Thank you!

**Comment by RX14** [comment]
I think i discovered *why* I hated it so much though, the hover-select mode clashes with drag on move because it lets you drag any item without having to click on it first. A good default would be to disable drag to move always when you're in hover select mode, and retain the option to disable it always.
