### ISSUE TITLE
Feature request: change silkscreen color in 3D Preview

### ISSUE THREAD

**Issue by bsilver8192** [horizon-eda/horizon#594]
I plan to make some PCBs with white soldermask and black silkscreen. My mechanically inclined teammates would like a preview with black silkscreen text, because white silkscreen on white soldermask is pretty useless. A color chooser like the one for the soldermask would be awesome.

**Comment by carrotIndustries** [comment]
Will be part of the next release: https://github.com/horizon-eda/horizon/pull/573
