### ISSUE TITLE
Horizon EDA vs EasyEDA part database

### ISSUE THREAD

**Issue by bob-u** [horizon-eda/horizon#597]
My circuits board projects are simple enough to be made with EasyEDA but complex enough that changes/updates are PITA.  I like how Horizon EDA operates, looks and routes but I am lazy to create/manage parts.

Can Horizon EDA parts database/part picking/management be ever as big and easy to use as EasyEDA?   What is the goal or intended workflow?

**Comment by carrotIndustries** [comment]
This isn't really an actionable issue, please continue the discussion on https://horizon-eda.discourse.group/
