### ISSUE TITLE
Update planes ignores polygons

### ISSUE THREAD

**Issue by frmdstryr** [horizon-eda/horizon#599]
I'm trying to smoothly join two different track widths with a polygon but probably doing it wrong...

![image](https://user-images.githubusercontent.com/380158/119007374-2ba1fc80-b95f-11eb-98ae-14143c581c69.png)

When I update the ground plane it seems to ignore the polygons and overlaps the polygons I added.

![overlap](https://user-images.githubusercontent.com/380158/119007798-8f2c2a00-b95f-11eb-8b40-d451a54c8f1c.png)

**Comment by frmdstryr** [comment]
As suggsted on IRC, I tried selecting it and using "Add plane" then setting the net. But it just doesn't fill it.

![image](https://user-images.githubusercontent.com/380158/119009897-93594700-b961-11eb-89ce-83ebe1d9546b.png)

After update all planes

![image](https://user-images.githubusercontent.com/380158/119010080-b3890600-b961-11eb-8e15-c844af6bbe70.png)

**Comment by frmdstryr** [comment]
Decided to just draw a bunch of overlapping tracks...

**Comment by carrotIndustries** [comment]
You might try keeping orphans enabled to prevent it from deleting the fragment that isn't connected to anything.

Thinking a bit further, I think there could be value in properly supporting non-plane polygons on copper layers with a net assigned to them, for example for making RF structures or things as in this issue.
