### ISSUE TITLE
Bug: created planes ignore rules

### ISSUE THREAD

**Issue by jue89** [horizon-eda/horizon#600]
Version: 87453a983db1a1273ee320f112ebe564691e2339

1. create a new board
2. open rules and enable thermal relief for planes
3. place a part
4. add a plane that is connected to one of the part's pad

The thermal relief is missing!

Work around:

1. open rules and click `Apply Rules`
2. update all planes

**Comment by carrotIndustries** [comment]
The better fix would be if the dialog would update the rules as the users selects the net, but I wasn't comfortable with adding that a few days prior to the 2.0 release.

Before editing the new plane, the tool sets the default plane settings as specified by the rules. When the user has picked the net, the tools updates the settings as specified by the rules.
