### ISSUE TITLE
Feature request: Omit 3D-model of a single part

### ISSUE THREAD

**Issue by trembel** [horizon-eda/horizon#603]
Sometimes a component - although placed - will not be soldered on the PCB (e.g. a Pin Header). It would be nice if there would be, analogous to "Omit Silkscreen" a button to omit the 3D view of a part.

**Comment by carrotIndustries** [comment]
Isn't that what the "do not populate" option in the schematic is for?

**Comment by tkornack** [comment]
It would be useful to (optionally?) hide the 3D model for parts that are DNP.

**Comment by carrotIndustries** [comment]
> It would be useful to (optionally?) hide the 3D model for parts that are DNP.

That option already exists and is the default.

**Comment by tkornack** [comment]
My apologies! Indeed, now I see it working!

Perhaps close this issue?
