### ISSUE TITLE
Feature request: Track fill

### ISSUE THREAD

**Issue by frmdstryr** [horizon-eda/horizon#610]
It would be nice if there was a way to define the outline of a track then do a "track fill" where inside the outline track would be filled with a plane and defined by the track outline. Similar to a how a plane works but instead of a polygon the outline would be a set of connected tracks.  

![image](https://user-images.githubusercontent.com/380158/125458835-c252183c-fe46-4cc2-9db5-bc971b73e035.png)

**Comment by RX14** [comment]
I personally havent come across needing this in many PCB designs of my own, and it's definitely possible in the rare cases where it comes up with a poly pour. What are the reasons you're using tracks (or even a pour at all) instead of a poly pour here?

**Comment by frmdstryr** [comment]
No real reason I guess... just found doing an outline with tracks to leverage the autorouter, then drawing a polygon connecting all points of works better, but it gets annoying to manually update the polygon whenever I want to adjust something and thought a way to automatically fill might be nice.

Might not make sense, idk.

**Comment by bob-u** [comment]
Snap polygon to track shape?  How would you define which track segments to snap to?

Something like this: https://desktop.arcgis.com/en/arcmap/10.3/manage-data/editing-fundamentals/reshaping-a-polygon-to-match-another-feature.htm?

Would it be easier to implement copper pour attached (sharing coords) to track (of same net) segments?

**Comment by unrelentingtech** [comment]
Maybe there should be an option to have the outer plane just *not* skip areas surrounded by tracks? And then have airwires between these discontinuous segments of the plane to make sure the user connects them through vias and stuff?

**Comment by RX14** [comment]
> Maybe there should be an option to have the outer plane just _not_ skip areas surrounded by tracks? And then have airwires between these discontinuous segments of the plane to make sure the user connects them through vias and stuff?

If you connect via vias then the plane gets filled. I think for this usecase having a visual check that all places you want filled are filled is enough.

**Comment by carrotIndustries** [comment]
I also don't really see why one would need this and don't have a good idea how to implement it.

**Comment by unrelentingtech** [comment]
> If you connect via vias then the plane gets filled

Oh nice! This is one of those non-obvious things that are really good to know. ~~We really need a Microsoft Clippy to pop up with these tips.~~
