### ISSUE TITLE
Rule to check that labels match pin names?

### ISSUE THREAD

**Issue by frmdstryr** [horizon-eda/horizon#611]
After spending time reflowing chips and tinking with wiring and code wondering why my board didn't work I realized I had accidentally swapped net labels on the schematic and produced boards with the screen prints messed up... 

![image](https://user-images.githubusercontent.com/380158/126877354-817aed17-bbd6-44e8-ac04-ec50135f08ce.png)

What made it more confusing/hard to find is that the board editor view shows the net label on the pin instead of the pin name.

![image](https://user-images.githubusercontent.com/380158/126878031-aa10eef9-c015-45e5-9dd6-c9f0b9bd4a04.png)

Aside from having a better review process... is there any way that horizon could help check this? 

I was thinking of possibly:

1. A rule that checks if the net name doesn't equal the pin name 
2. Have an option to toggle pin names from the schematic

Any thoughts or ideas?

**Comment by carrotIndustries** [comment]
> Any thoughts or ideas?

I don't see an easy option how this wouldn't generate too many false positives.
