### ISSUE TITLE
gcc-8, g++-8 required to compile

### ISSUE THREAD

**Issue by bob-u** [horizon-eda/horizon#613]
On Ubuntu 18.4 I had to install gcc-8 and g++8 in order to compile.   `<filesystem>` is supported by gcc 8, where as gcc 7 requires `<experimental/filesystem>`

`sudo apt install  gcc-8 g++-8 `
`sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 80 --slave /usr/bin/g++ g++ /usr/bin/g++-8 --slave /usr/bin/gcov gcov /usr/bin/gcov-8`

to show default gcc:
`sudo update-alternatives --config gcc`

EDIT: I also had to add` --enabled-shared `as I was getting error when linking objects:

`requires dynamic R_X86_64_PC32 reloc against 'sqrt' which may overflow at runtime; recompile with -fPIC`

**Comment by carrotIndustries** [comment]
> On Ubuntu 18.4 I had to install gcc-8 and g++8 in order to compile.

This is mentioned in the docs: https://docs.horizon-eda.org/en/latest/build-linux.html

> The C++ compiler needs to support std::filesystem, for GCC this requires version 8 or newer.


> EDIT: I also had to add--enabled-sharedas I was getting error when linking objects

The ubuntu 18.04 pipeline works just fine: https://github.com/horizon-eda/horizon/runs/3714713445?check_suite_focus=true
