### ISSUE TITLE
Exception when pool database file is missing

### ISSUE THREAD

**Issue by moritz-meier** [horizon-eda/horizon#614]
Adding an existing pool though _Welcome to Horizon -> Use existing pool_ does not update the pool.
If the pool database file is missing (e.g. in a freshly cloned pool) it leads to following exception in the _Installed Pools_ window when selecting the pool on left side:

`std::exception: unable to open database file`

I think Horizon should probably check if the pool database file exists and do an pool update when necessary (the user can probably delete the database file at any time by accident).
Maybe also do a pool update when adding an existing pool.

**Comment by kermitdafrog8** [comment]
Sounds about what I'm experiencing.  Also if I open the app in a console it shows a segmentation fault if I try to get the pool data with the app.
