### ISSUE TITLE
Scaling broken on wayland

### ISSUE THREAD

**Issue by RX14** [horizon-eda/horizon#617]
I'm using horizon eda https://github.com/horizon-eda/horizon/commit/987724c79949204b095990db0fae6349dabe1ac6, and 2x scaling seems to be broken in wayland. I'm using a ryzen mobile laptop with sway 1.6.1 as the compositor.

Unscaled:
![poomf-linux-2021-10-16T18 03 10](https://user-images.githubusercontent.com/2788811/137594325-f4081879-73ae-4012-84e1-c700110cfad4.png)

On a scaling 2 monitor:
![poomf-linux-2021-10-16T18 03 16](https://user-images.githubusercontent.com/2788811/137594322-39ed98c4-e325-4706-8616-12cbb752e232.png)

**Comment by carrotIndustries** [comment]
It works on X11 (and win32 as far as I'm aware).

What's the return value of `get_scale_factor` there?  https://github.com/horizon-eda/horizon/blob/2d1a7a181a398d30214f573a1b92c03a3b67aeeb/src/canvas/canvas_gl.cpp#L155-L159

**Comment by unrelentingtech** [comment]
I haven't seen this issue, running a 2x scale monitor on [Wayfire](https://wayfire.org/) — schematic, board, 3D all look fine.

![Screen_2021-12-04-01:49:23](https://user-images.githubusercontent.com/208340/144682887-f711079a-9438-4fcc-a354-3da9c7238fbd.png)

(and just checked the current git version, it's still fine)

It's *very* weird for such a bug to only happen on some setups…

**Comment by RX14** [comment]
What GPU do you have @unrelentingtech ?

**Comment by unrelentingtech** [comment]
Vega 56

```
AMD -- Radeon RX Vega (vega10, LLVM 12.0.1, DRM 3.37, 14.0-CURRENT)
Mesa 22.0.0-devel (git-8abfd58ffa)
```

**Comment by RX14** [comment]
> I doubt GPU differences would cause this

GL is surprisingly variable between vendors... Unlikely in this case since we're both on AMD though.

I'm unlikely to debug this again until I get a 2x scaling display again, I'm back on 1x ones now.

**Comment by RX14** [comment]
Seems like it was a GTK bug, and is fixed.
