### ISSUE TITLE
Keep-out Polygon Problem

### ISSUE THREAD

**Issue by oldrev** [horizon-eda/horizon#622]
Hello:

First, Horizon EDA is very impressive, I can’t imagine how much effort you all put into developing this bad boy, the rotation function in board editor that kills.

At this very moment, I'm trying to draw a simple MCU board, I found the keep-out polygon seems to have no effect on the poured plane in board editor, but it does the job in 3D preview window, see the following pictures:

![image](https://user-images.githubusercontent.com/188374/141060046-3a043579-e683-4c09-bea3-813f38f9f7a2.png)

![image](https://user-images.githubusercontent.com/188374/141059976-c5b6baa3-5dbe-421f-9dc5-a02cbeffe382.png)

And yes, I did "Update all planes".

So, my stupid question is: is this a feature or a bug?

Env: Horizon EDA CI 2021-11-09 on Windows 10.

Cheers!

**Comment by carrotIndustries** [comment]
This is probably the same issue as https://github.com/horizon-eda/horizon/issues/313. The problem is that keepouts are drawn identically to planes.

**Comment by oldrev** [comment]
> This is probably the same issue as #313. The problem is that keepouts are drawn identically to planes.

Thanks for the quick reply, so the workaround solution for the current version is net color?

**Comment by carrotIndustries** [comment]
I'll try to implement drawing keepouts as outline only in the next week or so.

On the long run, we want something like per-type fill patterns to make them easier to distinguish.

**Comment by oldrev** [comment]
Sounds great, can't wait for the next release.
