### ISSUE TITLE
Silk screen not rendered over tented via in 3d view

### ISSUE THREAD

**Issue by frmdstryr** [horizon-eda/horizon#630]
If silkscreen is placed over a tented via the center is omitted in the 3d view.

![image](https://user-images.githubusercontent.com/380158/144074965-21732789-3801-4ad4-af29-ee88a8812346.png)

**Comment by carrotIndustries** [comment]
Right now, holes are subtracted from all layers except solder mask. What'd be the correct way to achieve your desired effect? Intersect solder mask (it's negative) with holes before subtracting them from silkscreen?

**Comment by frmdstryr** [comment]
I was hoping to contribute a PR but after looking at the code I was not sure how to determine if the hole is for a tented via or not as that seems to come from the pool? 

The easiest approach (if my understanding is correct...) would be to add some way to skip adding the hole to the subtraction path at https://github.com/horizon-eda/horizon/blob/master/src/canvas3d/canvas_mesh.cpp#L188.  I haven't spent enough time in the code to know the best approach.  

Another case to consider that would need a similar check would be blind and buried vias.

Perhaps the hole could have a stop and start layer parameters? So the start layer of a hole could be less than the top silkscreen for a tented via.

**Comment by carrotIndustries** [comment]
> Another case to consider that would need a similar check would be blind and buried vias.

These aren't supported at all right now.

We shouldn't look at the via it self, only at the resulting geometry. Let's think of it that way: Silkscreen doesn't float in air (apart from when it extends beyond the board's outline), so there must be something underneath it. 

| Hole | Solder mask (inverted, there is no soldermask where the soldermask layer is) | Silkscreen |
|--|--|--|
|Yes|Yes| Hole not covered by soldermask, so no |
|Yes|No| Hole covered by soldermask, so yes|
|No|Yes| Not a hole, so yes|
|No|no| Not a hole, so yes|

> I haven't spent enough time in the code to know the best approach.

For silkscreen, union all holes and intersect the union with the solder mask layer.

**Comment by frmdstryr** [comment]
Somehow I missed the last part of your first comment... that makes sense.

**Comment by RX14** [comment]
close this issue now the PR's been merged?

**Comment by frmdstryr** [comment]
Yes, thank you!
