### ISSUE TITLE
PCB-graphic-only parts shoud be ignored in BoM and PnP files

### ISSUE THREAD

**Issue by oldrev** [horizon-eda/horizon#632]
Hello:

Currently when I place a PCB antenna in the schematic then I have to mark it as "Do Not Pop" otherwise it will be presented in the generated BoM and PnP file. IMHO, a big "X" on the symbol of the antenna looks wired.

To fix this issue I suggest we could add more "fabrication attributes" in the part editor like KiCAD:

![image](https://user-images.githubusercontent.com/188374/144751010-2977f06a-80d9-4b23-82fa-933ac27b4b5d.png)

Additionally, an option in the PnP file exporting dialog that allows users to choose SMT-only or SMT+PHT would be much nicer.

**Comment by carrotIndustries** [comment]
> To fix this issue I suggest we could add more "fabrication attributes" in the part editor like KiCAD:

We already have that in the part editor: 
![2021-12-05-162642_394x186_scrot](https://user-images.githubusercontent.com/877304/144752850-61f8fe9d-2308-4a0d-9679-d9ddc46937a6.png)

> Additionally, an option in the PnP file exporting dialog that allows users to choose SMT-only or SMT+PHT would be much nicer.

Hm, in combination with "one file per side", that'd be 4 filename entries, not sure if that's really worth it.

**Comment by oldrev** [comment]
Oops, that embarrassing. Is just me or the GNOME style is a little wired for productive software: every widget is fat then you have to hide some treasures.

**Comment by oldrev** [comment]
By the way, the "1mm Copper Test Point" part in the official core pool didn't set those flags.

**Comment by RX14** [comment]
The flags are fairly new and not set for some older parts. PRs are welcome to the pool!
