### ISSUE TITLE
Bug: The "From rules" option for a plane can not be saved

### ISSUE THREAD

**Issue by oldrev** [horizon-eda/horizon#635]
Steps to reproduce:

1. Uncheck the "From rules" option for a plane:

![1639026151(1)](https://user-images.githubusercontent.com/188374/145337464-9e76f6b6-db91-4870-a31a-986a6b44423b.png)

2. Save and close the board editor.

3. Reopen the board editor and this option still remains checked.

![image](https://user-images.githubusercontent.com/188374/145337508-31500df2-adc1-42f8-8872-4b9bc7029b40.png)

Horizon EDA version: 2.1.0 Green Flash "Commit 5677df4 2021-12-05 00:38:21 +0100 kicad symbol import: treat coordinates as signed"

**Comment by carrotIndustries** [comment]
Derp, wondering why no one noticed this in the past 4 years.

**Comment by oldrev** [comment]
> Derp, wondering why no one noticed this in the past 4 years.

Thanks for the quick fix that save my day.
