### ISSUE TITLE
Weird behavior with alignment tool and rotated text

### ISSUE THREAD

**Issue by frmdstryr** [horizon-eda/horizon#642]
Minor issue but If text is rotated the alignment tool behaves in an unexpected way.

![Peek 2022-01-01 12-57](https://user-images.githubusercontent.com/380158/147857087-52ffeeb4-e5e4-47e6-afd2-108d166e0388.gif)

**Comment by carrotIndustries** [comment]
This was lazy me not figuring out how to compute the bounding box of a text. Right now, there's no proper way to get an object's bounding box other than reaching into the canvas to get its selection box.

Fixing this would require some refactoring that I'm not comfortable doing before the upcoming release.
