### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by ovari** [horizon-eda/horizon#649]
Can your program please be translatable using a web-based interface, perhaps using [Hosted Weblate](https://hosted.weblate.org/)?

Thank you

**Comment by katyo** [comment]
@ovari IIRC currently internationalization does not supported at all.

**Comment by carrotIndustries** [comment]
> @ovari IIRC currently internationalization does not supported at all.

Exactly. I'm not convinced that translating Horizon EDA is a worthwhile effort.
