### ISSUE TITLE
Round off convex corner

### ISSUE THREAD

**Issue by tkornack** [horizon-eda/horizon#655]
It seems that the wonderful "Round off vertex" tool doesn't handle convex corners. This is what happens when I try it:

<img width="263" alt="image" src="https://user-images.githubusercontent.com/3050138/162105193-1c532fb0-da4e-4545-9cbf-78faf57fba6d.png">

Thanks for making horizon!

**Comment by carrotIndustries** [comment]
>. This is what happens when I try it:

Yeah, back then I couldn't quite figure out how to pick the arc orientation. Press <kbd>e</kbd> to flip the arc in the round off vertex tool.

**Comment by twarge** [comment]
oh, thanks!

**Comment by carrotIndustries** [comment]
> Yeah, back then I couldn't quite figure out how to pick the arc orientation

I had another thought about this and believe that the new implementation correctly handles all cases.
