### ISSUE TITLE
Feature request: resizable columns in various pool manager tables

### ISSUE THREAD

**Issue by twarge** [horizon-eda/horizon#659]
Some of the columns in the tables in the pool manager are not resizable for me. It would be handy to allow a wider column for the pin names in the unit editor for long FPGA pin names. 

<img width="510" alt="image" src="https://user-images.githubusercontent.com/101904407/168480974-25b1bfb0-2867-47c4-b502-6a1c19792ad4.png">

**Comment by carrotIndustries** [comment]
If the pin names are really long, they probably contain multiple functions that should be added as alternate names.

Making the columns resizable isn't quite straightforward unfortunately as the pin list is made from boxes and size groups rather than a treeview.

**Comment by twarge** [comment]
OK, thank you, I see. I will follow your 10M25 example.
