### ISSUE TITLE
Opening schematics leads to crashes

### ISSUE THREAD

**Issue by atoav** [horizon-eda/horizon#670]
On the latest `2.3.1 Iceblink` version (and the version `2.3.0` before that) the schematic editor/board editor crashes whenever I start it. I tried to load different pools, create a new project, etc. I am running the focal build from [the selfnet.de-mirror](https://mirror.selfnet.de/horizon-eda/ubuntu-focal/)

I am on `Ubuntu 20.04.4 LTS (Focal Fossa)` with Kernel `5.15.0`.

When I start horizon from the Terminal this is the Error message I get on stderr:

```
spawn /usr/bin/horizon-imp -c /home/d0/tmp/garbage/Test/blocks.json /home/d0/tmp/garbage/Test/pictures
/usr/bin/horizon-imp: symbol lookup error: /lib/x86_64-linux-gnu/libfreeimage.so.3: undefined symbol: _TIFFDataSize, version LIBTIFF_4.0
end proc 107452
```

In the editor it will display a `Editor for <PATH TO blocks.json> exited with status 32512` message.

**Comment by carrotIndustries** [comment]
Hm, interesting, I tried installing in a fresh docker container and I get until
```
terminate called after throwing an instance of 'horizon::SQLite::Error'
  what():  unable to open database file
```

By that point the dynamic linker has run.

Can you check the output of these two commands.
```
objdump -T /lib/x86_64-linux-gnu/libtiff.so.5 | grep TIFFData
ldd /usr/bin/horizon-imp | grep libtiff
```

**Comment by atoav** [comment]
Output of the mentioned command:

```
0000000000010940 g    DF .text  0000000000000018  LIBTIFF_4.0 TIFFDataWidth
        libtiff.so.5 => /lib/x86_64-linux-gnu/libtiff.so.5 (0x00007f7009fca000)
```

**Comment by carrotIndustries** [comment]
Interesting, on  a new docker docker container, I get this:
```
# objdump -T /lib/x86_64-linux-gnu/libtiff.so.5 | grep TIFFData
000000000000f6a0 g    DF .text	0000000000000018  LIBTIFF_4.0 TIFFDataWidth
000000000000f6c0 g    DF .text	0000000000000019  LIBTIFF_4.0 _TIFFDataSize
```
Note that it provides the `_TIFFDataSize` symbol. 

Here's my version of libtiff:

```
# apt-cache show libtiff5
Package: libtiff5
Architecture: amd64
Version: 4.1.0+git191117-2ubuntu0.20.04.3
```

I also downloaded the package from https://packages.ubuntu.com/focal/libtiff5 and verified that it also contains the symbol in question. The SHA256 hash of  `libtiff.so.5` is `9fe99c5f396784646d866bae000e31b929182e6a6caff212d7f289f390425fb6`

**Comment by atoav** [comment]
Well this could be the source of the problem:

In my case I seem to have the newer version `4.4.0`.

```
# apt-cache show libtiff5
apt-cache show libtiff5
Package: libtiff5
Source: tiff
Priority: optional
Section: libs
Installed-Size: 574
Maintainer: Laszlo Boszormenyi (GCS) <gcs@debian.org>
Architecture: amd64
Version: 4.4.0-0ubuntu1~20.04.sav0
...
```

**Comment by carrotIndustries** [comment]
> Version: 4.4.0-0ubuntu1~20.04.sav0

Where is that version from? I couldn't find it on packages.ubuntu.com

**Comment by atoav** [comment]
Aha, I installed Blender via the `http://ppa.launchpad.net/savoury1/blender/ubuntu focal/main amd64 Packages` PPA and this pulls in the version 4.4.0:  

```
# apt-cache policy libtiff5
libtiff5:
  Installed: 4.4.0-0ubuntu1~20.04.sav0
  Candidate: 4.4.0-0ubuntu1~20.04.sav0
  Version table:
 *** 4.4.0-0ubuntu1~20.04.sav0 500
        500 http://ppa.launchpad.net/savoury1/blender/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
...
```

**Comment by carrotIndustries** [comment]
> this pulls in the version 4.4.0

Ok, that's why people invented nix os ;)

You might also try the flatpak build.

> Maybe it is a good heads up for possible errors that lurk in the next version of libtiff5.

The issue is caused by the version freeimage of not being compiled against the right version of libtiff5, so nothing that we have to worry about.

**Comment by atoav** [comment]
> Ok, that's why people invented nix os ;)

It is on my list of things I want to check out at some point : )

> You might also try the flatpak build.

I will consider it.
