### ISSUE TITLE
Custom BOM and Pick and Place column names 

### ISSUE THREAD

**Issue by RX14** [horizon-eda/horizon#675]
JLCPCB expects specific, exact column names in the CPL and BOM csv files. It'd be nice to be able to save that as part of a project, so the csvs didn't have to be edited by hand afterwards.

Perhaps even export these settings as a save/loadable template to make sure you don't have to look up the names for every project. Perhaps even combine that with gerber export settings, so you can load manufacturer-specific export settings in a single file.

**Comment by carrotIndustries** [comment]
For the Pnp at least, that's supported: https://blog.horizon-eda.org/progress/2021/01/07/progress-2020-11-12.html#pickplace-export-format-customisation

Adding the same settings to the BOM export shouldn't be too hard.

**Comment by carrotIndustries** [comment]
See the linked branch, let me know if that works for you.

**Comment by RX14** [comment]
Tried it out, looks great! All fine to merge for me
