### ISSUE TITLE
STEP export fails with zero length polygon segments

### ISSUE THREAD

**Issue by tkornack** [horizon-eda/horizon#681]
It's not hard to inadvertently create a zero length polygon segment (click twice in the same spot), and generally it seems quite harmless:

<img width="435" alt="image" src="https://user-images.githubusercontent.com/3050138/182162378-584d70cd-ea16-4cd6-9381-277f6be2ef8c.png">

However, the STEP exporter fails with 

```
Board outline…
Board cutouts…
Holes…
Creating board…
Error: 0xffffaddaa3a0 : StdFail_NotDone: BRep_API: command not done

```

It's easy enough to fix once you know what's wrong, but I wonder if you could consider one of these:
- Check for zero length segments (either in Rules or in the STEP exporter)
- Automatically remove zero length segments

**Comment by carrotIndustries** [comment]
The recent commits on master address this in multiple ways:

 - The draw polygon tool doesn't create zero-length edges anymore when clicking twice on the same point
 - The STEP export removes zero-length edges
 - The preflight check checks for zero-length edges and flags them as a warning

**Comment by tkornack** [comment]
That's great!
