### ISSUE TITLE
gl error 1281 in src/canvas/triangle_renderer.cpp:120

### ISSUE THREAD

**Issue by b99** [horizon-eda/horizon#689]
My OS is Windows7 X64.
When Click on any one of the “Schematic / Board / Part Browser“ , in a while show the error:

gl error 1281 in src/canvas/triangle_renderer.cpp:120
Program will abort

The releases v2.3.1, and the last git version are same error.

**Comment by carrotIndustries** [comment]
That might be your GPU/drivers not supporting OpenGL 3.

Also, Windows 7 isn't supported by Horizon EDA as it's EOL and libraries are phasing out support for it as well: https://github.com/msys2/MINGW-packages/issues/10088 I should probably add this to the documentation.

**Comment by carrotIndustries** [comment]
> I should probably add this to the documentation.

Done: https://horizon-eda.readthedocs.io/en/latest/installation.html#windows
