### ISSUE TITLE
3D Flying parts with Jupiter - AMD Radeon driver issue on Windows

### ISSUE THREAD

**Issue by bob-u** [horizon-eda/horizon#691]
Congratulations on the new release.  I tried v2.4.0 version with example project x-transmitter and I got misplaced 3D parts in 3D preview:

![image](https://user-images.githubusercontent.com/61708771/196031875-08a770ff-e6e2-45f8-85cb-5f8260a64296.png)
![image](https://user-images.githubusercontent.com/61708771/196031909-a049bf3e-f365-4484-813f-925faaa4a932.png)

**Comment by carrotIndustries** [comment]
There were no changes to the 3D view from 2.3 to 2.4. To me this looks more like a driver issue since I've seen similar things happen on AMD GPUs on Windows.

**Comment by bob-u** [comment]
Yes, I'm on Windows and AMD Ryzen 5500.  I'll upgrade the drivers.

**Comment by bob-u** [comment]
I updated to the latest AMD driver dated 10/3/2022 (my old driver was from 2021) and reset all settings which resolved the issue.  All 3D components have returned to earth.

**Comment by carrotIndustries** [comment]
> I updated to the latest AMD driver dated 10/3/2022 (my old driver was from 2021) and reset all settings which resolved the issue. All 3D components have returned to Earth.

Ok, I guess we can close this issue then?

**Comment by bob-u** [comment]
Yes, it was a driver issue.
