### ISSUE TITLE
Failing to login to Github in pool manager

### ISSUE THREAD

**Issue by RX14** [horizon-eda/horizon#692]
Pool manager returns this error:
![poomf-linux-2022-10-25T12 43 39](https://user-images.githubusercontent.com/2788811/197753201-a046baa8-5e23-4eea-a53a-4fcea384b2a3.png)

Looks like an issue with the oauth flow.

**Comment by carrotIndustries** [comment]
Thanks, I changed the relevant setting in the app.

**Comment by RX14** [comment]
All fixed, thanks.
