### ISSUE TITLE
ld.gold: Changing linker on commandline

### ISSUE THREAD

**Issue by maikwoehl** [horizon-eda/horizon#693]
Is this variable ment to be overwritten from commandline - like `WITH_SPNAV`? Does it missing a `?` here?
https://github.com/horizon-eda/horizon/blob/750111e829cd6f3563ef8040c224ce147808c27d/Makefile#L958

As a maintainer for the package in Solus I've now included a patch to replace `-fuse-ld=gold` with `-fuse-ld=bfd` into my package build description and not using clang anymore.

https://dev.getsol.us/D13683

**Comment by carrotIndustries** [comment]
For me, `make GOLD=-fuse-ld=lld ` does work.

**Comment by maikwoehl** [comment]
Okay, I'll give it a try - maybe I've done something wrong or our build environment strips away that variables. Wouldn't be surprising. 

Thanks for your quick reply.
