### ISSUE TITLE
Editor exited with status 32512

### ISSUE THREAD

**Issue by oxplot** [horizon-eda/horizon#694]
Opening an existing project's board or schematics results in the following error in the UI:

```
Editor for '/home/mike/dev/pdpi/hardware/board.json"' exited with status 32512
```

and the following error in the terminal:

```
/usr/bin/horizon-imp: symbol lookup error: /usr/bin/horizon-imp: undefined symbol: _ZN24BRepBuilderAPI_MakeShape5BuildEv
end proc 16154
```

Environment:

 - Arch Linux (6.0.7-hardened1-1-hardened)
 - Horizon EDA: 2.4.0 Jupiter

**Comment by carrotIndustries** [comment]
This is caused by an incompatible opencascade upgrade. I've bumped the pkgrel of the AUR package to trigger a rebuild.
