### ISSUE TITLE
Crash: No GL implementation is available

### ISSUE THREAD

**Issue by akarpenko** [horizon-eda/horizon#700]
Opening schematic editor on Windows 11 (ARM) running on Parallels VM (macOS on M1 chip) results in:
```Glib::Error: No GL implementation is available```

**Comment by carrotIndustries** [comment]
Well, then the VM doesn't provide suitable graphics acceleration. Horizon EDA requires an OpenGL 3 or 4 capable GL implementation.

You might try your luck with https://docs.mesa3d.org/drivers/llvmpipe.html. 

Did you compile Horizon EDA on ARM or are you using x86 emulation?
