### ISSUE TITLE
Feature request: Support more than four internal copper layers

### ISSUE THREAD

**Issue by tkornack** [horizon-eda/horizon#701]
In my limited testing the present version of Horizon seem to support up to four internal copper layers for a maximum of a 6 layer board. It would be super useful to support more layers! 8 and 10 layer boards are quite helpful with dense BGAs. Hopefully it's not too challenging to support more layers?

Thanks for writing Horizon!

**Comment by carrotIndustries** [comment]
> Hopefully it's not too challenging to support more layers?

Not at all, i was just waiting for someone to ask for more inner layers. We now support up to 8 inner layers, which should be enough for now.
