### ISSUE TITLE
Applying, modifying a label to a wire does inconsistent things. 

### ISSUE THREAD

**Issue by indrora** [horizon-eda/horizon#702]
If I place two components down, then two net labels, then give each of them the same name, I get an error:

![image](https://user-images.githubusercontent.com/470584/212771916-51bfc417-0622-4bbe-a674-44f0a717506e.png)

These should be automatically merged in this scenario. Right now, I have to right click and guess which "move net to net" option I want to use, guess which `VBUS` is the one currently assigned, then wonder why this wasn't done automatically.

I cannot have a wire that is part of multiple nets, such as is available in KiCad: 

![image](https://user-images.githubusercontent.com/470584/212772765-c63eab25-6b3e-4e25-9a20-170b7405b063.png)

Finally, if I rename a net reference, it renames it on all labels, not just the one I've modified:

https://user-images.githubusercontent.com/470584/212775232-bbde9c18-57fd-403c-a7ba-cefa083851c1.mp4

This could have a catastrophic effect if I mislabel (VBUS/VBATT, in this example) one component and then suddenly the rest of the labels similar to it mislabel themselves when I fix the label in one place.

**Comment by carrotIndustries** [comment]
This behavior is intentional due to the explicit handling of nets: The property editor on the right deals with nets, not with net segments. That's why editing the name there changes the name everywhere.

Not implicitly merging nets by typing in names is a deliberate design decision since I've found this to lead to unintentional or missed connectivity in other tools.

This is probably something that should go into the to-be-created FAQ.

**Comment by indrora** [comment]
Then the UI should offer me a way to fix things without guessing. The instant I created this situation, it should have given me the opportunity to merge them: "Use Existing net `VBUS`?"

Renaming a net label should ask me if I want to do this for the whole net or just one label. If for some reason I had a larger schematic and had accidentally placed a label for "VBUS" somewhere but meant "VBATT", went "oh I should fix that" and suddenly tied everywhere that had a VBUS (which could be at 100VDC) to VBATT (which might be 3.3V) in schematic sheets I didn't think to check, now I've got a way bigger problem.

This sort of lack of usability puts Horizon at the level of "Would not recommend" in the same way that I wouldn't recommend Fritzing to someone.

**Comment by tkornack** [comment]
I, also as a new user, encountered this error. It is simply not the Horizon method for naming nets. If you are connecting to an existing net, you should draw the net and specify the name by pressing 'v'. I have found that this workflow reduces errors where you would make a mistake in naming two nets you meant to connect.

**Comment by tkornack** [comment]
Also, I think it's a reasonable design decision to have only one name for a net. But I think you can have two nets tied together with a net tie.

**Comment by RX14** [comment]
> Renaming a net label should ask me if I want to do this for the whole net or just one label. If for some reason I had a larger schematic and had accidentally placed a label for "VBUS" somewhere but meant "VBATT", went "oh I should fix that" and suddenly tied everywhere that had a VBUS (which could be at 100VDC) to VBATT (which might be 3.3V) in schematic sheets I didn't think to check, now I've got a way bigger problem.

I think you still misunderstand what's going on here. The nets would not tie in this situation, horizon would simply say there are two nets with the same name. Merging and splitting nets is *always* explicit. Nets are referred by with an internal ID in Horizon, which is explicitly managed. This is different to other schematic software which labels nets with a name and counts any net segments with the same name as the same net.

I suggest you play around with it some more, it is a different system if you are coming from another piece of software, but it prevents errors and makes many net actions explicit and easily reversible which would be easy to miss in other software.
