### ISSUE TITLE
Crash on creation of new symbol

### ISSUE THREAD

**Issue by LHSmicius** [horizon-eda/horizon#708]
Strange... First symbol I created with no problem, but now it always crashing. I rebuilded from source several times, recloned pool, changed projects - nothing helped.
Steps to reproduce:
1. Open Pool manager tab "Symbols".
2. Create.
3. Chose any unit from the list. (e.x.I used NE555 and many more)
4. Double click any unused pin. This gives an exception.

_0   | Critical| Core                    | exception thrown in tool constructor of Place pin; [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal_

![image](https://user-images.githubusercontent.com/46829407/219871642-bc560140-6687-41c1-826b-8245382be6c0.png)

tested with commit 85514df on February 18 2023. Debian 11 Linux.

**Comment by carrotIndustries** [comment]
This was caused by a corrupted tool setting in ` ~/.config/horizon/tool_settings/` . The linked commit handles errors while loading tool settings more gracefully.
