### ISSUE TITLE
Footprint generator generates incorrect pitch

### ISSUE THREAD

**Issue by LHSmicius** [horizon-eda/horizon#751]
I found that pitch calculation works incorrectly with SO, PSON and QFN packages (didn't test much yet) and it works good with SON package. Here are some examples.
SO:
![image](https://github.com/horizon-eda/horizon/assets/46829407/542a5333-4cd6-4c96-8ae9-75674aa2f376)
![image](https://github.com/horizon-eda/horizon/assets/46829407/ac263e63-e8b1-46a5-b474-40209496cbd4)

PSON:
![image](https://github.com/horizon-eda/horizon/assets/46829407/324fbb05-1ddc-4608-9739-8f2260ffa9ad)
![image](https://github.com/horizon-eda/horizon/assets/46829407/521e5fec-0d70-42f6-993e-5debdc1acdbe)

QFN:
![image](https://github.com/horizon-eda/horizon/assets/46829407/e5d52c51-ddea-49ad-8585-31d98ee0985b)
![image](https://github.com/horizon-eda/horizon/assets/46829407/a7714730-5cd7-4eb1-9775-34bf54c017d6)

SON works good (also tried pitch 0.65 and 1.27), but same problem with pitch 0.655 (rounds to 0.65 or 0.66):
![image](https://github.com/horizon-eda/horizon/assets/46829407/02e30016-2368-437d-b570-6f1ab7ffcacc)
![image](https://github.com/horizon-eda/horizon/assets/46829407/0749868e-4479-4471-92ff-269ab8872457)

Same issue mentioned in https://github.com/horizon-eda/horizon-pool/pull/334
Issue exists on commit 2023-10-04 fff71347d40bf6180e947512ede23f43a5a6cc80 and older (tested 2023-05).

**Comment by frmdstryr** [comment]
Can you try changing round off to none?

**Comment by LHSmicius** [comment]
> Can you try changing round off to none?
It helped. This trick solved the problem in all cases.

What actually this round-off feature suppose to do?

**Comment by carrotIndustries** [comment]
> What actually this round-off feature suppose to do?

It says so in the tip at the bottom of the window:

> All features of the land pattern is rounded to this value, including pad sizes and placement.

IIRC it's an IPC thing.

**Comment by LHSmicius** [comment]
Ok... That explains everything... Sorry for creating this nooby issue.
