### ISSUE TITLE
Copy/paste of arcs does not translate arc center

### ISSUE THREAD

**Issue by tkornack** [horizon-eda/horizon#772]
1. Open a new board. 
2. Use the net tool to draw a track with a curved segment
3. Select all 
4. Copy
5. Move cursor to a new location
6. Paste
7. Observe error in arc segment. 

It seems that the arc center does not get translated to the new location when pasting. Paste does work faithfully if you paste at the same coordinate that you copied, and then move it to the new location.

**Comment by tkornack** [comment]
![image](https://github.com/horizon-eda/horizon/assets/3050138/9a532850-421e-40b7-9c87-550ba793c39d)

**Comment by carrotIndustries** [comment]
Thanks, just in time for the upcoming 2.6 release!
