### ISSUE TITLE
Orphaned plane pours under blind vias

### ISSUE THREAD

**Issue by tkornack** [horizon-eda/horizon#773]
A plane underneath a micro via still fills as though the via were connected. The rules check correctly identifies the fill as unconnected. 

To reproduce: create a three-layer board with two nets; ground and signal and place vias as shown. The middle and bottom layers have the signal layer
<img width="447" alt="image" src="https://github.com/horizon-eda/horizon/assets/3050138/0fff4471-28fb-4806-9460-450511ffa561">

The blind via correctly connects to the middle layer
<img width="538" alt="image" src="https://github.com/horizon-eda/horizon/assets/3050138/7550f901-0b63-40ca-a67a-5b1caf1f4764">

But the bottom layer is filled wrongly
<img width="426" alt="image" src="https://github.com/horizon-eda/horizon/assets/3050138/7147d223-f300-4af3-b977-f0df9731f65e">

**Comment by carrotIndustries** [comment]
Does the linked branch fix it for you?

**Comment by tkornack** [comment]
Yes!
