### ISSUE TITLE
Debian repo: signing key expired

### ISSUE THREAD

**Issue by your-friend-alice** [horizon-eda/horizon#776]
The signing key (`8D3D7343BE30F701C20E83CF3BFF2011B242BF0C`, linked from the [Debian install instructions](https://horizon-eda.readthedocs.io/en/latest/installation.html?highlight=debian#debian-ubuntu) expired on 2024-05-24, breaking `apt-get update` for any machines with this repo added.

**Comment by carrotIndustries** [comment]
Thanks for the reminder, extended the GPG key: https://github.com/horizon-eda/horizon-eda.org/commit/0884989ca540c326d38d5653c0da3292e62654ae
